### ISSUE TITLE
[Bug : Tour Book View] SQLException

### ISSUE THREAD

**Issue by mluttermoeller** [mytourbook/mytourbook#1022]
### What happened ?

I updated from to version 23.3.0. Since I get an error when I select a tour. This message appears every time you select a tour.

![2023-03-14 07_51_56-Touren Liste - MyTourbook - 23 3 0](https://user-images.githubusercontent.com/89929817/224921404-961107d9-4557-4094-a59b-2a300b77342c.png)

### Version

23.3.0

### System

Windows

### Relevant log output

```shell
!ENTRY net.tourbook.common 4 0 2023-03-14 07:52:27.160
!MESSAGE SQL statement: 

1     SELECT
2     jTdataTtag.TOURTAG_TAGID,
3     SUM(tourData.TOURDISTANCE) AS TOTALDISTANCE,
4     SUM(tourData.TOURDEVICETIME_RECORDED) AS TOTALRECORDEDTIME
5     FROM TOURDATA_TOURTAG jTdataTtag
6     INNER JOIN TOURDATA
7     ON jTdataTtag.TOURDATA_TOURID = tourData.TOURID
8     GROUP BY jTdataTtag.TOURTAG_TAGID


SQLException

SQLState: 22003
ErrorCode: 20000
Message: Der resultierende Wert liegt außerhalb des Bereichs für den Datentyp INTEGER.


!ENTRY net.tourbook.common 4 0 2023-03-14 07:52:27.161
!MESSAGE Der resultierende Wert liegt außerhalb des Bereichs für den Datentyp INTEGER.
!STACK 0
ERROR 22003: Der resultierende Wert liegt außerhalb des Bereichs für den Datentyp INTEGER.
	at org.apache.derby.client.am.CrossConverters.getIntFromLong(Unknown Source)
	at org.apache.derby.client.am.Cursor.getInt(Unknown Source)
	at org.apache.derby.client.am.ClientResultSet.getInt(Unknown Source)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getInt(NewProxyResultSet.java:2547)
	at net.tourbook.tag.TagManager.fetchTourTagsAccumulatedValues(TagManager.java:402)
	at net.tourbook.ui.UI.updateUI_TagsWithImage(UI.java:1268)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.updateUI_Tab_1_Tour(TourDataEditorView.java:9364)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.updateUI_FromModelRunnable(TourDataEditorView.java:9031)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView$43.run(TourDataEditorView.java:8990)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by wolfgang-ch** [comment]
Your recorded time for a tag was larger than

* 214'7483'647 seconds or
* 596’523 hours or
* 24’855 days

I'll fix it
