### ISSUE TITLE
[Tagging Pref Page] Exception occurs when double clicking the column separator

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1033]
### What happened ?

@FJBDev Do you know which view it caused ?

### Version

23.10.0

### System

Linux

### Relevant log output

```shell
I had several times those exceptions:

Unhandled event loop exception

org.eclipse.core.runtime.AssertionFailedException: assertion failed:
at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
at org.eclipse.jface.viewers.ColumnPixelData.<init>(ColumnPixelData.java:81)
at org.eclipse.jface.viewers.ColumnPixelData.<init>(ColumnPixelData.java:51)
at org.eclipse.jface.layout.TreeColumnLayout.updateColumnData(TreeColumnLayout.java:144)
at org.eclipse.jface.layout.AbstractColumnLayout.lambda$0(AbstractColumnLayout.java:76)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1534)
at org.eclipse.swt.widgets.TreeColumn.gtk_size_allocate(TreeColumn.java:425)
at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2445)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:6114)
at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4474)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
at org.eclipse.jface.window.Window.open(Window.java:799)
at net.tourbook.application.ActionHandler_OpenDialog_Preferences.execute(ActionHandler_OpenDialog_Preferences.java:37)
at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
at net.tourbook.application.Application.start(Application.java:35)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by FJBDev** [comment]
I think I found how to reproduce it and on which view it happens.

I can reproduce it every time on my Debian but not on Windows

Scenario:
- Open the preferences page
- select the `Tagging` menu
- Double click on the red highlighted bars to automatically resize the columns
- The error will show in the error log

So it could be an SWT bug since i don't see where in the MT code the issue is ?

![image](https://user-images.githubusercontent.com/25235665/226758220-4beb971e-2d49-46fc-8291-e311be1bab45.png)

**Comment by wolfgang-ch** [comment]
The same issue occur with Ubuntu.

When debugging this issue then the column width returns `-1` when double clicking the column separator, this causes the exception

![image](https://user-images.githubusercontent.com/1283445/226930267-85be5857-2f7c-47a9-a7e7-5a864249d65e.png)

**Comment by FJBDev** [comment]
I saw the same thing when debugging on my Debian.

Additionally, after more investigation, it seems that it happens only when using a `TreeViewer` since it also happens in those preference pages:
- [3D Map layers](https://github.com/mytourbook/mytourbook/blob/6d8435a95fee1a54bacf81ec42595c724931f589/bundles/net.tourbook/src/net/tourbook/map3/ui/Map3LayerUI.java#L287)

but not all the `TreeViewer` since it doesn't occur in :
- [2D Map Provider](https://github.com/mytourbook/mytourbook/blob/6d8435a95fee1a54bacf81ec42595c724931f589/bundles/net.tourbook/src/de/byteholder/geoclipse/mapprovider/DialogMPProfile.java#L556)

Also, it doesn't seem to be related to only the **23.3.0** release but seems to be an existing problems for a while so maybe it's not critical to release **23.3.1**

**Comment by wolfgang-ch** [comment]
> Also, it doesn't seem to be related to only the **23.3.0** release but seems to be an existing problems for a while so maybe it's not critical to release **23.3.1**

This issue exists propably since ever (or an eclipse version change) -> it's not critical for 23.3.1
