### ISSUE TITLE
[Bug : EasyImport] "this.distanceSerie" is null

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1044]
### What happened ?

When trying to import a tour from pdd file (Polar) in 23.3.2 I received the following error:
![Bildschirmfoto vom 2023-03-28 23-33-26](https://user-images.githubusercontent.com/127450598/228375699-60cd955e-aefd-465e-9795-f639132d36eb.png)

I'm not sure how it was in 23.3.1, but I'm pretty sure it still worked in 23.3.0...
[Edit]
I just tried version 23.3.1. still working there... the bug must have sneaked in with version 23.3.2

### Version

23.3.2

### System

Linux

### Relevant log output

```shell
!ENTRY net.tourbook.common 4 0 2023-03-28 23:29:34.620
!MESSAGE Cannot load from float array because "this.distanceSerie" is null
!STACK 0
java.lang.NullPointerException: Cannot load from float array because "this.distanceSerie" is null
	at net.tourbook.data.TourData.computeAltitudeUpDown_20_Algorithm_DP(TourData.java:2935)
	at net.tourbook.data.TourData.computeAltitudeUpDown(TourData.java:2852)
	at net.tourbook.data.TourData.computeAltitudeUpDown(TourData.java:2816)
	at net.tourbook.data.TourData.computeAltitudeUpDown(TourData.java:2763)
	at net.tourbook.device.polar.hrm.Polar_HRM_Data.createTourData(Polar_HRM_Data.java:512)
	at net.tourbook.device.polar.hrm.Polar_HRM_Data.parseSection(Polar_HRM_Data.java:915)
	at net.tourbook.device.polar.hrm.Polar_HRM_DataReader.processDeviceData(Polar_HRM_DataReader.java:95)
	at net.tourbook.device.polar.hrm.Polar_PDD_Data.createExercise_10_ImportSeparatedFile(Polar_PDD_Data.java:283)
	at net.tourbook.device.polar.hrm.Polar_PDD_Data.createExercise(Polar_PDD_Data.java:184)
	at net.tourbook.device.polar.hrm.Polar_PDD_Data.parseSection20ExerciseInfo(Polar_PDD_Data.java:927)
	at net.tourbook.device.polar.hrm.Polar_PDD_Data.parseSection(Polar_PDD_Data.java:505)
	at net.tourbook.device.polar.hrm.Polar_PDD_DataReader.processDeviceData(Polar_PDD_DataReader.java:104)
	at net.tourbook.importdata.RawDataManager.importTours_FromOneFile_10(RawDataManager.java:2601)
	at net.tourbook.importdata.RawDataManager.lambda$8(RawDataManager.java:2485)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:57)
	at net.tourbook.importdata.RawDataManager.importTours_FromOneFile(RawDataManager.java:2398)
	at net.tourbook.importdata.RawDataManager.importTours_FromMultipleFiles_30_OneFile(RawDataManager.java:2262)
	at net.tourbook.importdata.RawDataManager.lambda$6(RawDataManager.java:2231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

!ENTRY net.tourbook.common 4 0 2023-03-28 23:29:34.627
!MESSAGE incorrect header check
!STACK 0
java.util.zip.ZipException: incorrect header check
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:105)
	at net.tourbook.device.crp.ZLibCompressionHelper.decompress(ZLibCompressionHelper.java:41)
	at net.tourbook.device.crp.CRPDataReader.getRawFilePath(CRPDataReader.java:198)
	at net.tourbook.device.crp.CRPDataReader.validateRawData(CRPDataReader.java:522)
	at net.tourbook.importdata.RawDataManager.importTours_FromOneFile_10(RawDataManager.java:2569)
	at net.tourbook.importdata.RawDataManager.lambda$8(RawDataManager.java:2485)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:57)
	at net.tourbook.importdata.RawDataManager.importTours_FromOneFile(RawDataManager.java:2398)
	at net.tourbook.importdata.RawDataManager.importTours_FromMultipleFiles_30_OneFile(RawDataManager.java:2262)
	at net.tourbook.importdata.RawDataManager.lambda$6(RawDataManager.java:2231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

!ENTRY net.tourbook.common 1 0 2023-03-28 23:29:51.266
!MESSAGE 2023-03-28T23:29:51.186738449  Setting all views closeable="true" in workbench.xmi
2023-03-28T23:29:51.186820366  workbenchFolderPath:    /home/xxx/.mytourbook/.metadata/.plugins/org.eclipse.e4.workbench
2023-03-28T23:29:51.264196292  numViews:               69
2023-03-28T23:29:51.266024585  closeable='true' is set in 0 views
```

**Comment by FJBDev** [comment]
I wish i had `pdd` files as it would have allowed me to have unit tests for it and maybe catch issues like this one before the release (assuming it is an actual regression issue in 23.3.2) but as you can see [here](https://github.com/mytourbook/mytourbook/discussions/939), i am still missing files for the  `pdd` format.

Can you share a file so i can reproduce and investigate locally?

**Comment by Thompson-ongithub** [comment]
[mytourbook_error_pddhrm.zip](https://github.com/mytourbook/mytourbook/files/11101895/mytourbook_error_pddhrm.zip)

I inserted 2 of those files... hrm being the actual exercise and pdd being the polar daily diary file...

**Comment by FJBDev** [comment]
@Thompson-ongithub thanks for the files, I am able to reproduce the issue and it seems that [this commit](https://github.com/mytourbook/mytourbook/commit/6ef486d703c50f48600317f6368c9a7411b38caf) introduced the regression issue. I will let @wolfgang-ch comment as he authored the commit.

One question though: Do you agree that I use your files so they can be used in the MT's unit tests in order to avoid those possible regressions in the future ?

**Comment by Thompson-ongithub** [comment]
> One question though: Do you agree that I use your files so they can be used in the MT's unit tests in order to avoid those possible regressions in the future ?

Yes, you can have those files for future testing.
For the time being I reverted to 23.3.1, so right now I'm fine.

Thanks for the work with MTB, it's a great program

**Comment by wolfgang-ch** [comment]
Is fixed in the next version
