### ISSUE TITLE
[Bug : Tour Tag Filter Slideout] java.lang.NullPointerException: Cannot invoke "net.tourbook.data.TourTag.getTagName()" because "tourTag" is null

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1075]
### What happened ?

I experienced this issue twice in the main branch but can't reproduce it

### Version

23.next

### System

Windows

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "net.tourbook.data.TourTag.getTagName()" because "tourTag" is null
Cannot invoke "net.tourbook.data.TourTag.getTagName()" because "tourTag" is null
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.updateTags_TagCloud(SlideoutTourTagFilter.java:2313)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.update_FromProfile(SlideoutTourTagFilter.java:2251)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.onProfile_Select(SlideoutTourTagFilter.java:1814)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter$6.selectionChanged(SlideoutTourTagFilter.java:714)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2128)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1660)
	at org.eclipse.jface.viewers.TableViewer.setSelection(TableViewer.java:165)
	at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:376)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.selectProfile(SlideoutTourTagFilter.java:2240)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.restoreState(SlideoutTourTagFilter.java:2210)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.createSlideoutContent(SlideoutTourTagFilter.java:521)
	at net.tourbook.common.tooltip.AdvancedSlideout.createUI(AdvancedSlideout.java:235)
	at net.tourbook.common.tooltip.AdvancedSlideout.createSlideoutContentArea(AdvancedSlideout.java:210)
	at net.tourbook.common.tooltip.AdvancedSlideoutShell.createUI(AdvancedSlideoutShell.java:724)
	at net.tourbook.common.tooltip.AdvancedSlideoutShell.showShell(AdvancedSlideoutShell.java:1732)
	at net.tourbook.common.tooltip.AdvancedSlideout.open_Runnable(AdvancedSlideout.java:546)
	at net.tourbook.common.tooltip.AdvancedSlideout$WaitTimer.run(AdvancedSlideout.java:133)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4152)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3272)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by wolfgang-ch** [comment]
When I discover such an error and it is not easy detectable why it occurred, I do just a simple NPE fix, in this case

![image](https://user-images.githubusercontent.com/1283445/233544456-e1d2c0f0-c929-4b29-a0b7-c0793fbf0b67.png)

**Comment by FJBDev** [comment]
> When I discover such an error and it is not easy detectable why it occurred, I do just a simple NPE fix, in this case
> 

I can definitely do that but I prefer creating an issue in case you know about a possible root cause.

**Comment by wolfgang-ch** [comment]
> > When I discover such an error and it is not easy detectable why it occurred, I do just a simple NPE fix, in this case
> 
> I can definitely do that...

Yes 

> ...but I prefer creating an issue in case you know about a possible root cause.

This is OK

**Comment by FJBDev** [comment]
Fixed in [this PR](https://github.com/mytourbook/mytourbook/pull/1083)
