### ISSUE TITLE
[Bug : Java17 on Windows] 

### ISSUE THREAD

**Issue by telemaxx** [mytourbook/mytourbook#1082]
### What happened ?

After upgrading from JDK11 to JDK17 i get a lot exception while startup.

But at the end MTB is running.

I would like to use jdk17, because with the latest eclipse it is the prerequisite.

Now i tried MTB 23.3.0 with the embedded Java 11 and JDK 17
No Errors anymore.
Good that @wolfgang-ch created such a version with embedded Java.
Now i can use the latest JDK 17, latest eclipse and latest MTB 23.3.2

On my Linux developing system i stay at JDK 11, because i was happy that i get it running with map25...

### Version

23.3.2

### System

Windows

### Relevant log output

```shell
the #### JDK 17 ##### part is at the end...

######################### JDK 11 log end with this: ###########################

12:23:06,638  INFO SettingsFactory:324 - Default entity-mode: pojo
12:23:06,638  INFO SettingsFactory:328 - Named query checking : enabled
12:23:06,666  INFO SessionFactoryImpl:193 - building session factory
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/C:/Users/top/.eclipse/1027998707_win32_win32_x86_64/configuration/org.eclipse.osgi/24/0/.cp/lib/hibernate-core-3.3.2/lib/required/javassist-3.9.0.GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
12:23:06,856  INFO SessionFactoryObjectFactory:105 - Not binding factory to JNDI, no JNDI name configured
12:23:05.491[Derby command executed] jdbc:derby:tourbook
12:23:05.491[DB Update] Current database DATA version: 48
12:23:06.099[Splash message] Vollenden...
Warning: NLS unused message: BlockedJobsDialog_UserInterfaceTreeElement in: org.eclipse.ui.internal.progress.messages
Application started in : 10167ms
net.tourbook.srtm.ElevationFile - open \C:\Users\top\mytourbook\srtm3\N52E009.hgt
12:23:10.304'483 [TourData] createSRTMDataSerie() - used srtm1 Values: 0, used srtm3 Values: 10004, replaced "wrong" Values: 0

######################### With JDK 17: ##############################

12:34:13,320  INFO SettingsFactory:324 - Default entity-mode: pojo
12:34:13,320  INFO SettingsFactory:328 - Named query checking : enabled
12:34:13,342  INFO SessionFactoryImpl:193 - building session factory
12:34:13,394 ERROR BasicLazyInitializer:165 - Javassist Enhancement failed: net.tourbook.data.TourBike
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7c871ce4
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:102)
        at javassist.util.proxy.FactoryHelper.toClass2(FactoryHelper.java:180)
        at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:163)
        at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:339)
        at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:314)
        at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:273)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.getProxyFactory(JavassistLazyInitializer.java:162)
        ... 195 more

##### this block repeated 195 times....   ######

12:34:13,607  INFO SessionFactoryObjectFactory:105 - Not binding factory to JNDI, no JNDI name configured
12:34:12.481[Derby command executed] jdbc:derby:tourbook
12:34:12.481[DB Update] Current database DATA version: 48
12:34:13.848[Splash message] Vollenden...
Warning: NLS unused message: BlockedJobsDialog_UserInterfaceTreeElement in: org.eclipse.ui.internal.progress.messages
Application started in : 6899ms
net.tourbook.srtm.ElevationFile - open \C:\Users\top\mytourbook\srtm3\N52E009.hgt
12:34:16.883'228 [TourData] createSRTMDataSerie() - used srtm1 Values: 0, used srtm3 Values: 10004, replaced "wrong" Values: 0
```

**Comment by wolfgang-ch** [comment]
>##### this block repeated 195 times....   ######

I've only 28 hits 😄 

![image](https://user-images.githubusercontent.com/1283445/235360175-47d72105-d762-4eb7-9f9f-70b9a1f6647b.png)

These 2 lines helped to not show the messages https://stackoverflow.com/questions/69218106/eclipse-not-able-to-open-java-files-unable-to-make-protected-final-java-lang#answer-69226134

![image](https://user-images.githubusercontent.com/1283445/235360753-d673b719-d91e-41e8-8080-e280b96135f5.png)

**Comment by telemaxx** [comment]
now i have looked in
C:\Program Files\MyTourbook
and i saw and edited eclipse.ini

than i deinstalled MT with the embedded java.
After that the eclipse.ini was also gone.

Than i installed MT without the embedded java.
But now no eclipse.ini was created.

![grafik](https://user-images.githubusercontent.com/22706487/235420192-c583bd3f-e669-4e65-aac9-1f47d5c33f56.png)

so i did the modification in mytourbook.ini but it did not solved the problem with the exceptions.
maybe i have to create the eclipse.ini manually?

Strange.

for now i will used the embedded version

**Comment by wolfgang-ch** [comment]
> Java 17 comes with nice [new coding features ](https://www.baeldung.com/java-migrate-8-to-17) that I started "playing with" 😄

I already saw that you used the new `instanceof` and `switch` features

**Comment by wolfgang-ch** [comment]
> @wolfgang-ch Can we use all the features existing in Java 17 or do you have a preference on new coding features that you don't want used in the MT code ?

I've not yet enogh experience with Java 17 to tell you what I don't like, but time will tell.
