### ISSUE TITLE
[Bug : Tour Calendar] Unhandled event loop exception

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1154]
### What happened ?

I see this the exception when trying to assign a tag to a tour from the Calendar View

### Version

23.5.0

### System

Linux

### Relevant log output

```shell
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Menu.checkNull(Menu.java:228)
	at org.eclipse.swt.widgets.Menu.<init>(Menu.java:125)
	at net.tourbook.tag.Action_AddTourTag_SubMenu.getMenu(Action_AddTourTag_SubMenu.java:501)
	at net.tourbook.common.util.AdvancedMenuForActions.openAdvancedMenu(AdvancedMenuForActions.java:311)
	at net.tourbook.tag.Action_AddTourTag_SubMenu.saveOrReopenTagMenu(Action_AddTourTag_SubMenu.java:564)
	at net.tourbook.tag.Action_AddTourTag_SubMenu.setTourTag(Action_AddTourTag_SubMenu.java:634)
	at net.tourbook.tag.TagMenuManager$ActionRecentTag.run(TagMenuManager.java:188)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by FJBDev** [comment]
@wolfgang-ch 

In 24.1 & 24.5, the exception doesn't occur anymore but I can't assign any tags to my tours. Any ideas why `parent` is null ? is it an SWT issue ? (Also, this only happens in Linux)

**Comment by FJBDev** [comment]
Actually, after more investigation, this is how i can reproduce the issue (Linux only):

- Open the contextual menu of a tour from the Calendar View
- Click on `Add Tags...` and the other contextual menu opens correctly :heavy_check_mark: 

- Try again using the mnemonic `A` and the tag menu will NOT open as the `parent` comes with a null value
![image](https://github.com/mytourbook/mytourbook/assets/25235665/74153c1e-345a-478e-9ce9-a44dbbdff74e)

**Comment by wolfgang-ch** [comment]
This is a very very advanced context menu which opens itself after a timeout, so I'm not wondering when there are issues.

When I debug it, and open the context menu manually, then in the first call the parent is null but the second contains the valid parent (on Windows)

You may try to open the context menu with Shift-F10 and test if it works on Linux

**Comment by FJBDev** [comment]
> You may try to open the context menu with Shift-F10 and test if it works on Linux

`Shift-F10` didn't work.
So far, I've found that it works only when clicking with the mouse or scrolling down with the keyboard arrow. The mnemonic method is the only one that does NOT work

**Comment by FJBDev** [comment]
The other weird part is that it works perfectly fine from the Tour Book View but not from the Calendar View

**Comment by wolfgang-ch** [comment]
The context menu in the tourbook view or other table/tree views is differently created than in the calendar view
