### ISSUE TITLE
[Import] Reimport a renamed tcx file does not change the importfilename in my tourbook anymore

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1171]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1170

<div type='discussions-op-text'>

<sup>Originally posted by **evdhoek** August 24, 2023</sup>
In the previous version before 23.8.0, after reimport a renamed tcx file, a helpscreen was shown with 4 options to adapt the new name into the database.
I do not know wheater it is has to do with the recent update, but now I do not see the helpscreen anymore and the importfilename in my tourbook is not changed anymore.
Old name already in MyTourbook: 20230617_1030 f Enschede-TechnBase+ 35.14
Changed into: 20230617_1030 f Enschede, NS-TechnBase+ 35.14
I hope someone can help.

After import I read In Tourlog: 
15:41:21 [main - 1] 1  Importing tours... 
15:41:21 [Importing tours - 54] 2 [TCX] C:\Users\elevd\OneDrive\Documents\.Garmin\.Import\20230617_1030 f Enschede, NS-TechnBase+ 35.14.tcx - is empty
15:41:21 [Importing tours - 54] 3 0.531 s ∙ 2,474 # ∙ 17/06/2023, 10:31 ← C:\Users\elevd\OneDrive\Documents\.Garmin\.Import\20230617_1030 f Enschede, NS-TechnBase+ 35.14.tcx
15:41:21 [Loading imported tours - 55] 4 [Skipped import file] C:\Users\elevd\OneDrive\Documents\.Garmin\.Import\20230617_1030 f Enschede, NS-TechnBase+ 35.14.tcx in tour 17/06/2023, 10:31
15:41:22 [main - 1] 5 Imported in 1.629 s
</div>

**Comment by wolfgang-ch** [comment]
When you run MT with the terminal output you will see this exception

```

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Label.computeSize(int, int)" because "this.imageLabel" is null
	at net.tourbook.common.dialog.MessageDialogWithRadioOptions.createCustomArea(MessageDialogWithRadioOptions.java:112)
	at org.eclipse.jface.dialogs.MessageDialog.createDialogArea(MessageDialog.java:335)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.createDialogAndButtonArea(IconAndMessageDialog.java:228)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.createContents(IconAndMessageDialog.java:207)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:609)
	at net.tourbook.importdata.RawDataManager.lambda$4(RawDataManager.java:1995)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
```



In Eclipse 4.25, some icons were removed in standard dialogs https://eclipse.dev/eclipse/news/4.25/platform.php#less-icons-in-user-dialogs and the code in MT, which is copied/modified from Eclipse, is causing this exception because MT before 23.8 was using Eclipse 4.24 which had not this issue.

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/mytourbook/mytourbook/commit/bc79a0585b81b3587cfca9b48eb531cca937625c
