### ISSUE TITLE
[Bug : Search Tours] A '(' character in the search text is causing an exception

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1181]
### What happened ?

This error occurs when searching for a tour with the text (without quotes) "(copy"

### Version

23.8

### System

All

### Relevant log output

```shell
!MESSAGE Cannot parse '(copy*': Encountered "<EOF>" at line 1, column 6.
Was expecting one of:
    <AND> ...
    <OR> ...
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    ")" ...
    "*" ...
    "^" ...
    <QUOTED> ...
    <TERM> ...
    <FUZZY_SLOP> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...

!STACK 0
org.apache.lucene.queryparser.classic.ParseException: Encountered "<EOF>" at line 1, column 6.
Was expecting one of:
    <AND> ...
    <OR> ...
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    ")" ...
    "*" ...
    "^" ...
    <QUOTED> ...
    <TERM> ...
    <FUZZY_SLOP> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...

        at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:931)
        at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:813)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:360)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:244)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:215)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:109)
        at net.tourbook.search.FTSearchManager.search_10_Search_All(FTSearchManager.java:1238)
        at net.tourbook.search.FTSearchManager.search(FTSearchManager.java:1151)
        at net.tourbook.search.FTSearchManager.searchByPosition(FTSearchManager.java:1553)
        at net.tourbook.search.SearchManager.xhr_Search(SearchManager.java:1273)
        at net.tourbook.search.SearchManager.handleXHREvent(SearchManager.java:1072)
        at net.tourbook.web.WebContentServer.handle_XHR(WebContentServer.java:590)
        at net.tourbook.web.WebContentServer.handle(WebContentServer.java:353)
        at net.tourbook.web.WebContentServer$DefaultHandler.handle(WebContentServer.java:232)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at net.tourbook.web.RequestParameterFilter.doFilter(RequestParameterFilter.java:46)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by wolfgang-ch** [comment]
The [Special characters](https://lucene.apache.org/core/4_10_3/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Escaping_Special_Characters
) `+ - && || ! ( ) { } [ ] ^ " ~ * ? : \ /` are ignored when they are escaped or not. They should be recognized when _Use ease searching_ is disabled.




![image](https://github.com/mytourbook/mytourbook/assets/1283445/bda19998-92d3-46d1-b365-1bb8cf768f27)

**Comment by wolfgang-ch** [comment]
It's not planned to fix this issue because it's a very rarely case
