### ISSUE TITLE
[Bug : Tour Blog View] NPE when editing the tour description

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1195]
### What happened ?

When clicking on the button to edit the tour description from the Tour Blog View, I get this NPE.

![image](https://github.com/mytourbook/mytourbook/assets/25235665/79f74ac4-73ff-4057-91fc-91df73a729e2)

### Version

23.10

### System

All

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "net.tourbook.data.TourData.getTourTitle()" because "this._tourData" is null
	at net.tourbook.tour.DialogQuickEdit.updateUIFromModel(DialogQuickEdit.java:973)
	at net.tourbook.tour.DialogQuickEdit.createDialogArea(DialogQuickEdit.java:174)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at net.tourbook.tour.DialogQuickEdit.create(DialogQuickEdit.java:144)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at net.tourbook.ui.views.TourBlogView.hrefActionEditTour(TourBlogView.java:816)
	at net.tourbook.ui.views.TourBlogView.onBrowserLocationChanging(TourBlogView.java:1005)
	at org.eclipse.swt.browser.LocationListener$1.changing(LocationListener.java:81)
	at org.eclipse.swt.browser.WebKit.webkit_decide_policy(WebKit.java:2304)
	at org.eclipse.swt.browser.WebKit.webViewProc(WebKit.java:616)
	at org.eclipse.swt.browser.WebKit.Proc(WebKit.java:537)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by FJBDev** [comment]
Scenario to reproduce the issue:

- Have a similar workspace as the below and make sure to start MT with the Tour Blog View open and the 2D Map Open
- Open the Tour Data Editor View
- Click on the "Edit tour description" in the Tour Blog View
- The NPE happens



![image](https://github.com/mytourbook/mytourbook/assets/25235665/84eb17e6-cc0b-4870-b6c9-36147aab7125)
