### ISSUE TITLE
[Bug : Unknown location] Unhandled event loop exception

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1202]
### What happened ?

This error happened to me when using 23.10 but I don't remember what caused it and I can't reproduce it

### Version

23.10

### System

All

### Relevant log output

```shell
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:480)
	at org.eclipse.swt.widgets.Menu.isVisible(Menu.java:1002)
	at net.tourbook.application.ContributionItem_TourType.openContextMenu(ContributionItem_TourType.java:382)
	at net.tourbook.application.ContributionItem_TourType$9.run(ContributionItem_TourType.java:437)
	at org.eclipse.swt.widgets.Display.timerProc(Display.java:5731)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.swt.widgets.Display.release(Display.java:4588)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:276)
	at net.tourbook.application.Application.start(Application.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/mytourbook/mytourbook/commit/ebbf7545f707da848c26ba9a8258ca606eb84d44
