### ISSUE TITLE
[Bug : Tour Tag Filter] Deleting a tag creates an NPE 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1203]
### What happened ?

Scenario:
- Create a tag filter with "Tag1"
- Delete "Tag1"
- The below NPE will occur as the tag doesn't exist anymore (maybe the tour tag filter should have been automatically updated?)

### Version

23.10

### System

All

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "net.tourbook.data.TourTag.getTagName()" because "tourTag" is null
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.updateTags_TagCloud(SlideoutTourTagFilter.java:2216)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.update_FromProfile(SlideoutTourTagFilter.java:2137)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.onProfile_Select(SlideoutTourTagFilter.java:1704)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.lambda$1(SlideoutTourTagFilter.java:697)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2128)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1660)
	at org.eclipse.jface.viewers.TableViewer.setSelection(TableViewer.java:165)
	at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:376)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.selectProfile(SlideoutTourTagFilter.java:2126)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.restoreState(SlideoutTourTagFilter.java:2096)
	at net.tourbook.tag.tour.filter.SlideoutTourTagFilter.createSlideoutContent(SlideoutTourTagFilter.java:507)
	at net.tourbook.common.tooltip.AdvancedSlideout.createUI(AdvancedSlideout.java:230)
	at net.tourbook.common.tooltip.AdvancedSlideout.createSlideoutContentArea(AdvancedSlideout.java:205)
	at net.tourbook.common.tooltip.AdvancedSlideoutShell.createUI(AdvancedSlideoutShell.java:724)
	at net.tourbook.common.tooltip.AdvancedSlideoutShell.showShell(AdvancedSlideoutShell.java:1740)
	at net.tourbook.common.tooltip.AdvancedSlideout.open_Runnable(AdvancedSlideout.java:531)
	at net.tourbook.common.tooltip.AdvancedSlideout$WaitTimer.run(AdvancedSlideout.java:131)
	at org.eclipse.swt.widgets.Display.timerProc(Display.java:5731)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/mytourbook/mytourbook/commit/e3806acb0fda603fc3f593892b6297ef60a3c090

> maybe the tour tag filter should have been automatically updated?

This would be the luxury fix which needs some work, I implemented a quick fix
