### ISSUE TITLE
[Bug : Map2] Unhandled event loop exception & Exception while dispatching event org.osgi.service.event.Event 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1233]
### What happened ?

The below exceptions happened in my MT production. 

I do not have a scenario to reproduce the errors

### Version

23.10

### System

Windows

### Relevant log output

```shell
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1278)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4800)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:64)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Control.redraw(Control.java:2428)
	at de.byteholder.geoclipse.map.Map2.grid_UpdateGeoGridData(Map2.java:2141)
	at de.byteholder.geoclipse.map.Map2.updateViewPortData(Map2.java:7817)
	at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:7357)
	at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:7254)
	at de.byteholder.geoclipse.map.Map2.setMapProvider(Map2.java:6998)
	at net.tourbook.map2.view.SlideoutMap2_MapProvider.selectMapProviderInTheMap(SlideoutMap2_MapProvider.java:1676)
	at net.tourbook.map2.view.SlideoutMap2_MapProvider.selectMapProvider_Internal(SlideoutMap2_MapProvider.java:1662)
	at net.tourbook.map2.view.SlideoutMap2_MapProvider.selectMapProvider(SlideoutMap2_MapProvider.java:1617)
	at net.tourbook.map2.action.ActionMap2_MapProvider.selectMapProvider(ActionMap2_MapProvider.java:95)
	at net.tourbook.map2.view.Map2View.restoreState(Map2View.java:4283)
	at net.tourbook.map2.view.Map2View.lambda$14(Map2View.java:1948)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.swt.widgets.Display.release(Display.java:3738)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:324)
	at net.tourbook.application.Application.start(Application.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by wolfgang-ch** [comment]
Added a fix but it is strange, that this issue happens in the `restore()` method when just the map was created. It's also strange that `Device is disposed` is fired
