### ISSUE TITLE
[Bug : 2D Map] Unhandled ConcurrentModificationException

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1245]
### What happened ?

The below error happened as I was looking at tours but I can't reproduce it

### Version

23.10

### System

All

### Relevant log output

```shell
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at de.byteholder.geoclipse.map.TileImageCache.dispose(TileImageCache.java:168)
	at de.byteholder.geoclipse.mapprovider.MP.resetAll(MP.java:1317)
	at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:7305)
	at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:7254)
	at net.tourbook.map2.view.Map2View.paintTours_20_One(Map2View.java:3901)
	at net.tourbook.map2.view.Map2View.paintTours_10_All(Map2View.java:3788)
	at net.tourbook.map2.view.Map2View.updateUI_ShowTour(Map2View.java:5257)
	at net.tourbook.map2.view.Map2View.onSelection_TourMarker(Map2View.java:3464)
	at net.tourbook.map2.view.Map2View.lambda$13(Map2View.java:1543)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1399)
	at net.tourbook.tour.TourManager.fireEventWithCustomData(TourManager.java:1416)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.fireSelection(TourMarkerAllView.java:1181)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.onSelect_TourMarker(TourMarkerAllView.java:1476)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by wolfgang-ch** [comment]
Sometimes I also have this issue but the tile image caching is too complex to easily fix this concurrent issue

**Comment by wolfgang-ch** [comment]
"Fixed" this issue by supressing the exception
