### ISSUE TITLE
[Bug : All Tour Marker View] Invalid Thread Access

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1263]
### What happened ?

After deleting 2 markers from the Marker View, I got this exception

![image](https://github.com/mytourbook/mytourbook/assets/25235665/341b4c52-4afe-477d-b7df-1689a21f9515)

![image](https://github.com/mytourbook/mytourbook/assets/25235665/a0c2a25b-d6d8-4c80-9385-d60c14f01a5b)

### Version

24.1

### System

Linux

### Relevant log output

```shell
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:338)
	at com.mchange.v2.c3p0.stmt.GooGooStatementCache.acquireStatement(GooGooStatementCache.java:569)
	at com.mchange.v2.c3p0.stmt.GooGooStatementCache.checkoutStatement(GooGooStatementCache.java:204)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.checkoutStatement(NewPooledConnection.java:321)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:553)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.loadAllMarker(TourMarkerAllView.java:1449)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.reloadViewer(TourMarkerAllView.java:1750)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.lambda$3(TourMarkerAllView.java:644)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1411)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1380)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:3066)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:2977)
	at net.tourbook.tour.ActionDeleteMarkerDialog.doAction(ActionDeleteMarkerDialog.java:119)
	at net.tourbook.tour.ActionDeleteMarkerDialog.lambda$2(ActionDeleteMarkerDialog.java:124)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at net.tourbook.tour.ActionDeleteMarkerDialog.run(ActionDeleteMarkerDialog.java:124)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.lambda$7(TourMarkerAllView.java:758)
	at org.eclipse.swt.events.KeyListener$1.keyPressed(KeyListener.java:66)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:171)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1577)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:937)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:4049)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:931)
	at org.eclipse.swt.widgets.Table.gtk_key_press_event(Table.java:2188)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2507)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6883)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:4193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6163)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)


org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1550)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:1001)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1751)
	at net.tourbook.tour.TourManager.checkTourData(TourManager.java:525)
	at net.tourbook.tour.TourManager.saveModifiedTours_OneTour(TourManager.java:3088)
	at net.tourbook.tour.TourManager$3.run(TourManager.java:3041)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by wolfgang-ch** [comment]
I think the root cause was from

`at net.tourbook.tour.TourManager.checkTourData(TourManager.java:525)`

which wanted to display a message box but it was running in a runnable with progress monitor

`at net.tourbook.tour.TourManager$3.run(TourManager.java:3041)`

I think we should check if a tour was modified in the tour editor before running such an action, like in other actions

```
      // check if the tour editor contains a modified tour
      if (TourManager.isTourEditorModified()) {
         return;
      }

```

**Comment by FJBDev** [comment]
> I think we should check if a tour was modified in the tour editor before running such an action, like in other actions
> 
> ```
>       // check if the tour editor contains a modified tour
>       if (TourManager.isTourEditorModified()) {
>          return;
>       }
> ```

It could be the culprit, though I don't recall having a tour modified when it happened.
Looking at the [action](https://github.com/mytourbook/mytourbook/blob/main/bundles/net.tourbook/src/net/tourbook/tour/ActionDeleteMarkerDialog.java), it doesn't seem that it performs the check as of today

**Comment by wolfgang-ch** [comment]
The action is now checking the tour editor. 

https://github.com/mytourbook/mytourbook/blob/d41b1882a000ec4b5607b87eb2d63395bf77322b/bundles/net.tourbook/src/net/tourbook/tour/ActionDeleteMarkerDialog.java#L87-L90


It is very difficult to find the reason when the tour data are not in sync but it occurs when the tour editor is open

`at net.tourbook.tour.TourManager.saveModifiedTours_OneTour(TourManager.java:3088)`
