### ISSUE TITLE
[Bug : EasyImport] An endless loop is filling up the console log when offline, every 11 ms

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1293]
### What happened ?

An endless loop is filling up the console log when offline, every 11 ms

Version: Commit 58b421f5b9cee156c4feba91fa52b2e94f0b83cf this the current main branch.

Should there be an option in the cloud pref dialog to disable a cloud provider / filesystems to be able, to stop a system which is runnig amok and makes it unusable ?

### Version

24.1

### System

All

### Relevant log output

```shell
!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.272
!MESSAGE ConnectException
!STACK 0
java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:378)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:93)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:343)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:475)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:380)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:449)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:439)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2673)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:294)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:654)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:552)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxClient.createDefaultDropboxClient(DropboxClient.java:126)
	at net.tourbook.cloud.dropbox.DropboxClient.<clinit>(DropboxClient.java:75)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.<init>(DropboxFileSystem.java:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at net.tourbook.common.FileSystemManager.readFileSystemsExtensions(FileSystemManager.java:214)
	at net.tourbook.common.FileSystemManager.getFileSystemsList(FileSystemManager.java:128)
	at net.tourbook.common.NIO.getFileStores(NIO.java:169)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.ui.views.rawData.RawDataView.lambda$35(RawDataView.java:6791)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)
	... 47 more

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.379
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.<init>(DropboxFileSystem.java:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at net.tourbook.common.FileSystemManager.readFileSystemsExtensions(FileSystemManager.java:214)
	at net.tourbook.common.FileSystemManager.getFileSystemsList(FileSystemManager.java:128)
	at net.tourbook.common.NIO.getFileStores(NIO.java:169)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.ui.views.rawData.RawDataView.lambda$35(RawDataView.java:6791)
	at java.base/java.lang.Thread.run(Thread.java:833)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.396
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.ui.views.rawData.RawDataView.lambda$35(RawDataView.java:6791)
	at java.base/java.lang.Thread.run(Thread.java:833)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.397
!MESSAGE ConnectException
!STACK 0
java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1055)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:378)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:93)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:343)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:475)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:380)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:449)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:439)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:157)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2673)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:294)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:654)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:552)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.<init>(DropboxFileSystem.java:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at net.tourbook.common.FileSystemManager.readFileSystemsExtensions(FileSystemManager.java:214)
	at net.tourbook.common.FileSystemManager.getFileSystemsList(FileSystemManager.java:128)
	at net.tourbook.common.NIO.getFileStores(NIO.java:169)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)
Caused by: java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)
	... 42 more

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.398
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.399
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.importdata.EasyImportManager.getImportFiles(EasyImportManager.java:379)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:230)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.401
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.402
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.importdata.EasyImportManager.getImportFiles(EasyImportManager.java:379)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:230)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.404
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.404
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.importdata.EasyImportManager.getImportFiles(EasyImportManager.java:379)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:230)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.405
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.406
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.importdata.EasyImportManager.getImportFiles(EasyImportManager.java:379)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:230)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.407
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.408
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.importdata.EasyImportManager.getImportFiles(EasyImportManager.java:379)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:230)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.408
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.408
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.common.NIO.convertToOSPath(NIO.java:73)
	at net.tourbook.importdata.ImportConfig.getOSFolder(ImportConfig.java:136)
	at net.tourbook.importdata.ImportConfig.getDeviceOSFolder(ImportConfig.java:116)
	at net.tourbook.importdata.EasyImportManager.getImportFiles(EasyImportManager.java:379)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:230)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)

!ENTRY net.tourbook.common 4 0 2024-02-16 09:47:47.408
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
	at net.tourbook.cloud.dropbox.DropboxClient.getTokens(DropboxClient.java:197)
	at net.tourbook.cloud.dropbox.DropboxClient.getValidTokens(DropboxClient.java:227)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.createDropboxFileSystem(DropboxFileSystem.java:118)
	at net.tourbook.cloud.dropbox.DropboxFileSystem.getFileStore(DropboxFileSystem.java:150)
	at net.tourbook.common.NIO.getFileStores(NIO.java:173)
	at net.tourbook.importdata.EasyImportManager.checkImportedFiles(EasyImportManager.java:193)
	at net.tourbook.ui.views.rawData.RawDataView$33.run(RawDataView.java:6993)
```

**Comment by FJBDev** [comment]
@wolfgang-ch 
I'll address this issue once I am done with [the nutrition feature](https://github.com/mytourbook/mytourbook/issues/1280)

**Comment by wolfgang-ch** [comment]
I continue this https://github.com/mytourbook/mytourbook/commit/032e84492ddf433834833481bb0a4ff9a7019dca#r140946949 discussion here

It's very easy to reproduce this issue;

* Unplug the network cabel from your computer  (and don't use WLAN 😄)
* Open the import view
* and the log is filling up immediatedly

**Comment by wolfgang-ch** [comment]
I just tested this issue, firstly I could reproduce but any other tries failed and it could not be reproduced

**Comment by FJBDev** [comment]
I understand it's easy to reproduce the issue, what i am not clear on is what the solution to implement is.

**Comment by wolfgang-ch** [comment]
When it's not easy to solve the connection code, then the user should be able, to disable this clould service:

* Add a checkbox in the pref page to enable/disable the cloud service
* When the cloud service is read in the code, then it should be skipped when it's disabled

![image](https://github.com/mytourbook/mytourbook/assets/1283445/035a5c35-67cb-4ae2-9a96-801dcc990354)

**Comment by FJBDev** [comment]
>It's very easy to reproduce this issue;
> I just tested this issue, firstly I could reproduce but any other tries failed and it could not be reproduced

After spending quite some time trying to reproduce the issue, it is not so "easy" and I couldn't reproduce on my 2 machines Debain 12 and Windows 11)
When I disconnect my Wifi, the log is not filling up

![image](https://github.com/mytourbook/mytourbook/assets/25235665/8c199e75-37df-41dc-b05e-8b4a560a9e91)

**Comment by FJBDev** [comment]
> When it's not easy to solve the connection code, then the user should be able, to disable this clould service:
> 
>     * Add a checkbox in the pref page to enable/disable the cloud service
> 
>     * When the cloud service is read in the code, then it should be skipped when it's disabled
> 
> 

Button to disable/enable the Dropbox file system is added in [this PR](https://github.com/mytourbook/mytourbook/pull/1329)
