### ISSUE TITLE
[Bug : Cloud Services] Find an alternative to Cyclic

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1337]
### What happened ?

@wolfgang-ch 

I found the unexpected bad news today as I noticed that all the cloud services in MT (weather, Strava...) are not working anymore.
Cyclic never sent me an email of their plan to shut it down so it came as an unexpected [news](https://app.cyclic.sh/#/)

Can we please delay 24.5 until I find an alternative ?

```
We are shutting down Cyclic.

In two weeks, May 10th, we will begin turning off free tier usage.

We will begin turning off all usage May 31.

It has been a great learning experience building the community and the company. However we were not able to sell enough to make it self sustaining. It is now time to turn off the service. Thanks for your support and we hope you enjoyed the service.

We apologize for any trouble for the short timeline.
```

### Version

24.5

### System

All

**Comment by FJBDev** [comment]
I already found a possible alternative that i will experiment very soon.

I wouldn't be surprised that user create issues describing cloud services not working

**Comment by FJBDev** [comment]
@wolfgang-ch Well, there might not be a need to delay 24.5. I migrated the app to [Render ](https://render.com/)and created a PR [here](https://github.com/mytourbook/mytourbook/pull/1338) 😄

**Comment by wolfgang-ch** [comment]
Tomorrow I'll create a new test version

**Comment by mff73** [comment]
Ready to test, thanks guys.

**Comment by wolfgang-ch** [comment]
@FJBDev Would it be possible to display an error message when connection fails, currently only the log has an entry

```java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Unknown Source)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at net.tourbook.weather.HistoricalWeatherRetriever.lambda$0(HistoricalWeatherRetriever.java:66)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at net.tourbook.weather.HistoricalWeatherRetriever.checkVendorConnection(HistoricalWeatherRetriever.java:57)
	at net.tourbook.ui.views.WeatherProvider_OpenWeatherMap.lambda$1(WeatherProvider_OpenWeatherMap.java:83)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at net.tourbook.application.ActionHandler_OpenDialog_Preferences.execute(ActionHandler_OpenDialog_Preferences.java:37)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

**Comment by FJBDev** [comment]
> @FJBDev Would it be possible to display an error message when connection fails, currently only the log has an entry

Its possible but i am jot a fan of blocking dialogs. The user should be able to see that the weather retrieval didnt work and can go in the log or error log to see more details

**Comment by FJBDev** [comment]
> Tomorrow I'll create a new test version

Perfect. Ive done testing already but ill test it more with the new test version

**Comment by wolfgang-ch** [comment]
> > @FJBDev Would it be possible to display an error message when connection fails, currently only the log has an entry
> 
> Its possible but i am not a fan of blocking dialogs. The user should be able to see that the weather retrieval didnt work and can go in the log or error log to see more details

We have the tour log view which can display an exception in the background and it is forced that exceptions will open the log view.

**Comment by wolfgang-ch** [comment]
I've create a new test version https://www.dropbox.com/sh/v6kni9jof54pg2m/AAB8wMp96vH8Q2fZ_saoUPxWa?dl=0

I tested the weather retrieval and it works again, however the first retrieval took more than 30 second

![image](https://github.com/mytourbook/mytourbook/assets/1283445/58116b62-6cb2-4bce-aae0-ba09da6c79ea)

**Comment by FJBDev** [comment]
> I tested the weather retrieval and it works again, however the first retrieval took more than 30 second

It likely means that the app instance was hibernating.
I subscribed to the free service of Render which has the below caveat:

![image](https://github.com/mytourbook/mytourbook/assets/25235665/d8df416b-ba55-4aad-bffb-38f22a3ead33)

**Comment by FJBDev** [comment]
I tested the latest test version of 24.5 and everything seems to be working fine for me 👍

**Comment by mff73** [comment]
cloud is also working fine for me with 24.5 test version

**Comment by stvzldn** [comment]
With version 24.7.0, get Weather now has a popup box with a Cancel button and progress bar.
When submitting a get Weather request that went beyond 2.5 minutes, I attempted the Cancel button.
However it did not cancel.  At about 5 minutes weather was retrieved and MTB again responded to user actions.

Would it be possible to get Weather asynchronously or to actually have the Cancel button do the cancel?
Image shows the greyed out Cancel button but MTB frozen on the get Weather.

![Weather does not cancel](https://github.com/user-attachments/assets/22514a3f-c1f1-40ec-887f-057eda808db3)

**Comment by FJBDev** [comment]
> Would it be possible to get Weather asynchronously or to actually have the Cancel button do the cancel? Image shows the greyed out Cancel button but MTB frozen on the get Weather.
> 

It might be technically possible to do it asynchronously but the issue I see is that if a user modifies a tour while the weather is being retrieved, that could create issues.
It's unfortunate that [Render ](https://render.com/) has this limitation but given we are using the free tier, I figured it's the best we can offer as of today.

**Comment by wolfgang-ch** [comment]
>  I attempted the Cancel button. However it did not cancel.

The cancel button can interrupt the weather retrieval between tours but not during the weather retrieval within a tour. So when the cancel button is pressed, the next tour will be canceled.

**Comment by stvzldn** [comment]
@FJBDev It is likely that I would modify the tour during asynch since I do weather fetch first and then tour edits.

@wolfgang-ch I assumed that is what Cancel would do since the box progress bar implies a count of tour weather fetched.

Sometimes weather fetch is almost immediate, often about the 50 seconds promised, but sometimes it is over two minutes.  However I am a patient user and can always find something else to do.

**Comment by wolfgang-ch** [comment]
>Sometimes weather fetch is almost immediate, often about the 50 seconds promised, 
but sometimes it is over two minutes. 

I have the same experience

> I assumed that is what Cancel would do since the box progress bar implies a count of tour weather fetched.

In the last version I changed the counter, the counter displayed e.g. 1/5 before the first weather was retrieved, now it shows 0/5
