### ISSUE TITLE
[Bug : 24.5.0 test version 20240513]  many errors in logs

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#1340]
### What happened ?

testing the 24.5 version from this morning (20240513)
in the log view, two entries are there from start, and are duplicating each time i am clicking somewhere in the log.
![image](https://github.com/mytourbook/mytourbook/assets/50132146/2d24c288-fce1-4447-9b7d-569a1f07939b)
 and then
![image](https://github.com/mytourbook/mytourbook/assets/50132146/4a8db756-920d-4f01-a42c-ef5dbbaea264)

Suunto cloud for one user did work, but when i switched to another user, i got this popup
![image](https://github.com/mytourbook/mytourbook/assets/50132146/63ef2442-db8a-4fd5-b7c5-9a058894d518)

### Version

24.5.0 from 20240513

### System

Windows

### Relevant log output

```shell
null
org.eclipse.e4.ui.workbench
Erreur
Mon May 13 07:42:37 CEST 2024
Cannot invoke "org.eclipse.swt.widgets.ToolItem.setImage(org.eclipse.swt.graphics.Image)" because "this._actionToolItem" is null

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.ToolItem.setImage(org.eclipse.swt.graphics.Image)" because "this._actionToolItem" is null
	at net.tourbook.common.tooltip.ActionToolbarSlideout.showOtherEnabledImage(ActionToolbarSlideout.java:364)
	at net.tourbook.map2.view.Map2View.syncMap_ShowCurrentSyncModeImage(Map2View.java:5239)
	at net.tourbook.map2.view.Map2View.enableActions(Map2View.java:2255)
	at net.tourbook.map2.view.Map2View.enableActions(Map2View.java:2180)
	at net.tourbook.map2.view.Map2View.onSelection(Map2View.java:3663)
	at net.tourbook.map2.view.Map2View.lambda$12(Map2View.java:1612)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:266)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:123)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:78)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$3.run(SelectionAggregator.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyPostListeners(SelectionAggregator.java:160)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.lambda$0(SelectionAggregator.java:250)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.changed(SelectionAggregator.java:250)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:358)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:374)
	at org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setPostSelection(SelectionServiceImpl.java:39)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$2(CompatibilityPart.java:132)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handleInvalidSelection(StructuredViewer.java:1141)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1411)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1459)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at org.eclipse.e4.ui.dialogs.filteredtree.FilteredTree$NotifyingTreeViewer.refresh(FilteredTree.java:790)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1418)
	at org.eclipse.e4.ui.dialogs.filteredtree.FilteredTree$NotifyingTreeViewer.refresh(FilteredTree.java:778)
	at org.eclipse.ui.internal.views.log.LogView.lambda$11(LogView.java:1175)
	at org.eclipse.jface.util.Throttler.lambda$0(Throttler.java:59)
	at org.eclipse.jface.util.Throttler.lambda$1(Throttler.java:67)
	at org.eclipse.jface.util.Throttler.throttledExec(Throttler.java:94)
	at org.eclipse.ui.internal.views.log.LogView.asyncRefresh(LogView.java:1210)
	at org.eclipse.ui.internal.views.log.LogView.lambda$4(LogView.java:843)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.views.log.LogView.handleClear(LogView.java:837)
	at org.eclipse.ui.internal.views.log.LogView.doDeleteLog(LogView.java:825)
	at org.eclipse.ui.internal.views.log.LogView$6.run(LogView.java:392)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)



null
org.eclipse.e4.ui.workbench
Erreur
Mon May 13 07:42:37 CEST 2024
Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench".

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.ToolItem.setImage(org.eclipse.swt.graphics.Image)" because "this._actionToolItem" is null
	at net.tourbook.common.tooltip.ActionToolbarSlideout.showOtherEnabledImage(ActionToolbarSlideout.java:364)
	at net.tourbook.map2.view.Map2View.syncMap_ShowCurrentSyncModeImage(Map2View.java:5239)
	at net.tourbook.map2.view.Map2View.enableActions(Map2View.java:2255)
	at net.tourbook.map2.view.Map2View.enableActions(Map2View.java:2180)
	at net.tourbook.map2.view.Map2View.onSelection(Map2View.java:3663)
	at net.tourbook.map2.view.Map2View.lambda$12(Map2View.java:1612)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:266)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:123)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:78)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$3.run(SelectionAggregator.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyPostListeners(SelectionAggregator.java:160)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.lambda$0(SelectionAggregator.java:250)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.changed(SelectionAggregator.java:250)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:358)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:374)
	at org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setPostSelection(SelectionServiceImpl.java:39)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$2(CompatibilityPart.java:132)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handleInvalidSelection(StructuredViewer.java:1141)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1411)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1459)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at org.eclipse.e4.ui.dialogs.filteredtree.FilteredTree$NotifyingTreeViewer.refresh(FilteredTree.java:790)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1418)
	at org.eclipse.e4.ui.dialogs.filteredtree.FilteredTree$NotifyingTreeViewer.refresh(FilteredTree.java:778)
	at org.eclipse.ui.internal.views.log.LogView.lambda$11(LogView.java:1175)
	at org.eclipse.jface.util.Throttler.lambda$0(Throttler.java:59)
	at org.eclipse.jface.util.Throttler.lambda$1(Throttler.java:67)
	at org.eclipse.jface.util.Throttler.throttledExec(Throttler.java:94)
	at org.eclipse.ui.internal.views.log.LogView.asyncRefresh(LogView.java:1210)
	at org.eclipse.ui.internal.views.log.LogView.lambda$4(LogView.java:843)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.views.log.LogView.handleClear(LogView.java:837)
	at org.eclipse.ui.internal.views.log.LogView.doDeleteLog(LogView.java:825)
	at org.eclipse.ui.internal.views.log.LogView$6.run(LogView.java:392)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)



null
org.eclipse.ui.workbench
Erreur
Mon May 13 07:44:02 CEST 2024
Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".

java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.ToolItem.setToolTipText(String)" because "this._actionToolItem" is null
	at net.tourbook.common.tooltip.ActionToolbarSlideout.setTooltip(ActionToolbarSlideout.java:339)
	at net.tourbook.ui.views.tourBook.TourBookView.enableActions(TourBookView.java:2374)
	at net.tourbook.ui.views.tourBook.TourBookView.lambda$1(TourBookView.java:1424)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:325)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:322)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:536)
	at net.tourbook.application.ContributionItem_Person.fireEventNewPersonIsSelected(ContributionItem_Person.java:169)
	at net.tourbook.application.ContributionItem_Person.onSelectPerson(ContributionItem_Person.java:187)
	at net.tourbook.application.ContributionItem_Person.lambda$2(ContributionItem_Person.java:135)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by mff73** [comment]
WAIT : i restarted this test version a couple of times, and still same issues. But after that, i started 24.1 official version, and : 
1- cloud was not working as expected.
2- when i restarted 24.5, now, there are no more errors in logs 🤔, and none are appearing.

Maybe something common between the two versions installed on my PC (two folders separated, with two different databases). But for the rest, i don't know.

I "installed" 24.5.0 with the zip file : deleting my previous folder content and copying the new one there.

**Comment by wolfgang-ch** [comment]
The above log entries may be subsequent errors.

Can you start MT with the console 

`"C:\Program Files\MyTourbook\mytourbook.exe" -debug -consolelog -showlocation` 

and try to reproduce the error and attach here the **whole** console log.

**Comment by FJBDev** [comment]
>  But after that, i started 24.1 official version, and : 1- cloud was not working as expected

Cloud is now only working in 24.5.

**Comment by wolfgang-ch** [comment]
You have added the eclipse log file but I need the output of the console which contains more info. When you run MT with the above parameters, then it looks like 

![image](https://github.com/mytourbook/mytourbook/assets/1283445/49013ff6-35ed-4ec5-b9c6-f03c06d27980)

**Comment by wolfgang-ch** [comment]
> please tell me where to find this console log).

There is no file, you have to copy/paste the output of the console into a text file

**Comment by wolfgang-ch** [comment]
> to reproduce my issues, I need to reset my personnal view (right clik on the view icon, and reset). Then the error log is getting filled.

I cannot reproduce this issue when resetting a perspective

![image](https://github.com/mytourbook/mytourbook/assets/1283445/02405bcd-2305-4065-ba5d-ccfc7f6ae00a)

**Comment by mff73** [comment]
sorry for my ignorance about the console ;)
Here are two files, one from 24.5 test version, and one from my official 24.1 version (same issue in fact). Surely not linked to 24.5 :(
[console log 24.5.txt](https://github.com/mytourbook/mytourbook/files/15307859/console.log.24.5.txt)
[console log 24.1.txt](https://github.com/mytourbook/mytourbook/files/15307860/console.log.24.1.txt)

**Comment by wolfgang-ch** [comment]
In you log files I cound not find any other errors but sometimes there is more info than in the eclipse log file.

I've fixed this issue and created a new test version, can you test it

https://www.dropbox.com/sh/v6kni9jof54pg2m/AAB8wMp96vH8Q2fZ_saoUPxWa?dl=0

**Comment by mff73** [comment]
thanks.
Version tested,  not the same errors, but still errors :( after own view reset.

[console log 24.5 bis.txt](https://github.com/mytourbook/mytourbook/files/15311920/console.log.24.5.bis.txt)

**Comment by wolfgang-ch** [comment]
Now there are 2 different issues

1. Similar like the previous, which I am fixing

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.ToolItem.setToolTipText(String)" because "this._actionToolItem" is null
        at net.tourbook.common.tooltip.ActionToolbarSlideout.setTooltip(ActionToolbarSlideout.java:339)
        at net.tourbook.ui.views.tourBook.TourBookView.enableActions(TourBookView.java:2374)
        at net.tourbook.ui.views.tourBook.TourBookView.fireTourSelection(TourBookView.java:2547)
        at net.tourbook.ui.views.tourBook.TourBookView.onSelect_NatTableItem(TourBookView.java:3532)
        at net.tourbook.ui.views.tourBook.TourBookView.lambda$10(TourBookView.java:1859)
```

2. It seems you are using an old perspective where the image is not any more available

```
java.io.FileNotFoundException: /icons/tour-map-compare-result-perspective.png
        at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
        at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
        at java.base/java.net.URL.openConnection(URL.java:1258)
        at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:115)

```

When I'm searching my PC it finds this image only in historic locations 

![image](https://github.com/mytourbook/mytourbook/assets/1283445/c3fed73c-0843-40e9-9f2a-6b45b843620a)

I've not yet found an easy way to delete a perspective, so I would recommend to create a new perspective and use this and not the old.

The not so easy way to remove a perspective is to edit the configuration file

`C:\Users\<YOUR NAME>\mytourbook\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi`

Make a backup of all your MT files and have fun with editing this file, but I don't recommend to do it.

**Comment by mff73** [comment]
thanks Wolfgang.
I edited workbench.xmi and deleted this old perspective in fault --> no more errors in the logs 😁👍
One last strange thing, probably related to perspective as well, because it is appearing when resetting another perspective : 
when i open MTB (24.5 test), my 2Dmap view has all the options icons on top : 
![image](https://github.com/mytourbook/mytourbook/assets/50132146/9ee6b922-63af-4ffc-b453-5bde816cef47)

if i reset my perspective, icons disappear
![image](https://github.com/mytourbook/mytourbook/assets/50132146/ed21bba1-a674-463b-826b-d62db5d95c45)

if i close 2D map and re open a new one, icons are there again.

Something corrupted again in this perspective ?

Thanks for all your efforts supporting 😉
Btw, 24.5 version seems to work fine after all 😊👌

**Comment by wolfgang-ch** [comment]
> Something corrupted again in this perspective ?

I've never had this issue, you may have corrupted it by modifying `workbench.xmi`

**Comment by mff73** [comment]
> > Something corrupted again in this perspective ?
> 
> I've never had this issue, you may have corrupted it by modifying `workbench.xmi`

i just did a total fresh installation, with mytourbook-24.5.0-win-setup-with-java-runtime.
Deleted any trace of old eclipse folders (i hope), any trace of old user data.
Just run MTB, with a totally new database, new user, everything new from scratch.

I just saved the current defaut perspective to a new one, and just reset it, and 2Dmap functions icons are disapearing, but also the ones from the easyimport view.
Before reset
![image](https://github.com/mytourbook/mytourbook/assets/50132146/b246522a-e4c6-444c-85f4-8be15f1079d8)

after reset
![image](https://github.com/mytourbook/mytourbook/assets/50132146/14623a5b-8680-42b1-876d-07d2b024e8f4)

**Comment by wolfgang-ch** [comment]
Resetting a perspective is a pure Eclipse feature, you may search the internet for bugs like https://www.google.com/search?q=eclipse+reset+perspective+bugs

**Comment by mff73** [comment]
ok, if resetting a perspective is buggy, then close a perspective and reopen it is doing the job. One click more, but quicker than searching for bugs in the internet for me 😉
Thanks Wolfgang, my 24.5.0 version is working fine. Going back to other adventures.

**Comment by mff73** [comment]
no more bugs
