### ISSUE TITLE
[Bug :  All Tour Marker View] NPE: Cannot load from object array because "monthData" is null

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1359]
### What happened ?

Those are the errors I saw when I tried to delete tour markers from the All Tour Marker View

### Version

24.5

### System

Linux

### Relevant log output

```shell
java.lang.NullPointerException: Cannot load from object array because "monthData" is null
	at net.tourbook.ui.views.calendar.CalendarTourDataProvider.getCalendarDayData(CalendarTourDataProvider.java:116)
	at net.tourbook.ui.views.calendar.CalendarGraph.drawCalendar(CalendarGraph.java:1249)
	at net.tourbook.ui.views.calendar.CalendarGraph.lambda$0(CalendarGraph.java:606)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3927)
	at org.eclipse.swt.widgets.Scrollable.gtk_draw(Scrollable.java:365)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:506)
	at org.eclipse.swt.widgets.Canvas.gtk_draw(Canvas.java:174)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2482)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6883)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6163)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:609)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:405)
	at org.eclipse.jface.dialogs.MessageDialog.openError(MessageDialog.java:491)
	at net.tourbook.common.util.SQL.showException(SQL.java:168)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.loadAllMarker(TourMarkerAllView.java:1468)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.reloadViewer(TourMarkerAllView.java:1711)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.lambda$3(TourMarkerAllView.java:609)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1411)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1380)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:3076)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:2987)
	at net.tourbook.tour.ActionDeleteMarkerDialog.doAction(ActionDeleteMarkerDialog.java:123)
	at net.tourbook.tour.ActionDeleteMarkerDialog.lambda$2(ActionDeleteMarkerDialog.java:128)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at net.tourbook.tour.ActionDeleteMarkerDialog.run(ActionDeleteMarkerDialog.java:128)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.lambda$7(TourMarkerAllView.java:722)
	at org.eclipse.swt.events.KeyListener$1.keyPressed(KeyListener.java:66)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:171)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1577)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:937)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:4049)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:931)
	at org.eclipse.swt.widgets.Table.gtk_key_press_event(Table.java:2188)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2507)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6883)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:4193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6163)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)


ERROR 08000: Connection closed by unknown interrupt.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.util.InterruptStatus.setInterrupted(Unknown Source)
	at org.apache.derby.iapi.util.InterruptStatus.throwIf(Unknown Source)
	at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.checkCancellationFlag(Unknown Source)
	at org.apache.derby.impl.sql.execute.BulkTableScanResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.next(Unknown Source)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:4745)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.loadAllMarker(TourMarkerAllView.java:1413)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.reloadViewer(TourMarkerAllView.java:1711)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.lambda$3(TourMarkerAllView.java:609)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1411)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1380)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:3076)
	at net.tourbook.tour.TourManager.saveModifiedTours(TourManager.java:2987)
	at net.tourbook.tour.ActionDeleteMarkerDialog.doAction(ActionDeleteMarkerDialog.java:123)
	at net.tourbook.tour.ActionDeleteMarkerDialog.lambda$2(ActionDeleteMarkerDialog.java:128)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at net.tourbook.tour.ActionDeleteMarkerDialog.run(ActionDeleteMarkerDialog.java:128)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.lambda$7(TourMarkerAllView.java:722)
	at org.eclipse.swt.events.KeyListener$1.keyPressed(KeyListener.java:66)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:171)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1577)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:937)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:4049)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:931)
	at org.eclipse.swt.widgets.Table.gtk_key_press_event(Table.java:2188)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2507)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6883)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:4193)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6163)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1597)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)





org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1550)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:1001)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1751)
	at net.tourbook.tour.TourManager.checkTourData(TourManager.java:525)
	at net.tourbook.tour.TourManager.saveModifiedTours_OneTour(TourManager.java:3098)
	at net.tourbook.tour.TourManager$3.run(TourManager.java:3051)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by wolfgang-ch** [comment]
I think these are subsequent bugs, the main bug is a sql exception which may be logged in the derby log file

```
	at net.tourbook.common.util.SQL.showException(SQL.java:168)
	at net.tourbook.ui.views.tourMarker.TourMarkerAllView.loadAllMarker(TourMarkerAllView.java:1468)
```
