### ISSUE TITLE
[Bug : 24.5 Test Build] Tests are failing in the build process

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1361]
```
[FATAL] Non-resolvable parent POM for net.tourbook:net.tourbook.ui.tests:24.5.0-SNAPSHOT: 
The following artifacts could not be resolved: net.tourbook:mytourbook-app:pom:24.5.0-SNAPSHOT (absent): 
Could not transfer artifact net.tourbook:mytourbook-app:pom:24.5.0-SNAPSHOT from/to swtbot (https://download.eclipse.org/technology/swtbot/releases/4.1.0/): 
Cannot access https://download.eclipse.org/technology/swtbot/releases/4.1.0/ with type p2 using the available connector factories: 
BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 14, column 12
```

https://github.com/mytourbook/mytourbook/blob/12a622074654e3f5799efb7135663d8ca80e528c/bundles/pom.xml#L40-L41

**Comment by FJBDev** [comment]
How do you reproduce this issue? Builds are running fine for me

**Comment by wolfgang-ch** [comment]
It was my fault, the test project was not open so the version number was not updated and this was the reason why it failed.

**Comment by FJBDev** [comment]
[The build](https://github.com/mytourbook/mytourbook/actions/runs/9495460329) is failing due to what seems to be a 2D map issue
```
!ENTRY net.tourbook.common 4 0 2024-06-13 07:36:56.790
!MESSAGE Cannot read field "width" because "this._backgroundImageSize" is null
!STACK 0
java.lang.NullPointerException: Cannot read field "width" because "this._backgroundImageSize" is null
	at de.byteholder.geoclipse.map.Map2.createBackgroundImage(Map2.java:1208)
	at de.byteholder.geoclipse.map.Map2.paint_40_MapPoints(Map2.java:5308)
	at de.byteholder.geoclipse.map.Map2.paint_10_PaintMapImage(Map2.java:5201)
	at de.byteholder.geoclipse.map.Map2.lambda$12(Map2.java:5129)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at de.byteholder.geoclipse.map.Map2.paint(Map2.java:5123)
	at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:10559)
	at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:10449)
	at net.tourbook.map2.view.Map2View.paintTours_20_One(Map2View.java:4296)
	at net.tourbook.map2.view.Map2View.paintToursAndPhotos(Map2View.java:4418)
	at net.tourbook.map2.view.Map2View.onSelectionChanged(Map2View.java:3645)
	at net.tourbook.map2.view.Map2View.lambda$14(Map2View.java:1746)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:266)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:123)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:78)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$3.run(SelectionAggregator.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator.notifyPostListeners(SelectionAggregator.java:160)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.lambda$0(SelectionAggregator.java:250)
	at org.eclipse.e4.core.contexts.RunAndTrack.runExternalCode(RunAndTrack.java:59)
	at org.eclipse.e4.ui.internal.workbench.SelectionAggregator$6.changed(SelectionAggregator.java:250)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:105)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:358)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:374)
	at org.eclipse.e4.ui.internal.workbench.SelectionServiceImpl.setPostSelection(SelectionServiceImpl.java:39)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.lambda$2(CompatibilityPart.java:132)
	at net.tourbook.common.util.PostSelectionProvider$1.run(PostSelectionProvider.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at net.tourbook.common.util.PostSelectionProvider.setSelection(PostSelectionProvider.java:160)
	at net.tourbook.ui.views.tourBook.TourBookView.fireTourSelection(TourBookView.java:2524)
	at net.tourbook.ui.views.tourBook.TourBookView.onSelect_TreeItem(TourBookView.java:3639)
	at net.tourbook.ui.views.tourBook.TourBookView.lambda$15(TourBookView.java:1989)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2128)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1176)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1205)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:263)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:421)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swtbot.swt.finder.widgets.AbstractSWTBot$2.run(AbstractSWTBot.java:193)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$5.doRun(UIThreadRunnable.java:224)
	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:90)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:33)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:127)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:42)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

**Comment by wolfgang-ch** [comment]
Did this happen during the app startup ?

**Comment by FJBDev** [comment]
> Did this happen during the app startup ?

I'm not sure
The build artifact [here ](https://github.com/mytourbook/mytourbook/actions/runs/9495460329/artifacts/1597035375)contains the log that might show when the failure happened

**Comment by wolfgang-ch** [comment]
It looks like that onResize() is not called very early from the swtbot to initialize the field "this._backgroundImageSize".

When this case would happen in the normal UI then I already would had this issue.

**Comment by FJBDev** [comment]
Also, the build is currently failing but it is due to an issue from SonarCloud. Looking at the [bug](https://sonarsource.atlassian.net/browse/SONARTEXT-164), it seems that it will be resolved soon

**Comment by FJBDev** [comment]
@wolfgang-ch When you modify tour import like the [TCX import, ](https://github.com/mytourbook/mytourbook/commit/8727004c858c6d88319577b0fe795137b83d12d0)this can break the unit tests as it seems that it did

![image](https://github.com/mytourbook/mytourbook/assets/25235665/4baff794-8e09-4844-8564-21ecd445abf4)

**Comment by wolfgang-ch** [comment]
I forgot the unit test for the import changes. I just fixed the issue that the marker elevation, latitude and longitures values were wrong.

I committed the new json file https://github.com/mytourbook/mytourbook/commit/3732fd0515a339ce63fdf8cfe090807f8f741833 but discovered that there are also some further whitespace modifications compared with the previous file.

**Comment by wolfgang-ch** [comment]
There is now a difference between my auto created test file and the created test file on the server.

I've no idea how to solve this

```
2024-06-25T07:33:50.3316644Z Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.638 s <<< FAILURE! - in GarminTCX DeviceDataReaderTests
2024-06-25T07:33:50.3316986Z device.garmin.GarminTCX_DeviceDataReaderTests.testTcxImportLyons  Time elapsed: 0.065 s
2024-06-25T07:33:50.3317306Z device.garmin.GarminTCX_DeviceDataReaderTests.testTcxPeloton  Time elapsed: 0.109 s
2024-06-25T07:33:50.3317725Z device.garmin.GarminTCX_DeviceDataReaderTests.testTcxImportConeyLake  Time elapsed: 0.235 s  <<< FAILURE!
2024-06-25T07:33:50.3317855Z org.opentest4j.AssertionFailedError: 
2024-06-25T07:33:50.3317943Z tourMarkers[0].latitude
2024-06-25T07:33:50.3318034Z Expected: 40.128272
2024-06-25T07:33:50.3318116Z      got: 40.135158
2024-06-25T07:33:50.3318254Z  ; tourMarkers[0].longitude
2024-06-25T07:33:50.3318380Z Expected: -105.592627
2024-06-25T07:33:50.3318489Z      got: -105.556992
2024-06-25T07:33:50.3318588Z  ; tourMarkers[1].latitude
2024-06-25T07:33:50.3318669Z Expected: 40.119869
2024-06-25T07:33:50.3318751Z      got: 40.136586
2024-06-25T07:33:50.3318839Z  ; tourMarkers[1].longitude
2024-06-25T07:33:50.3318959Z Expected: -105.608717
2024-06-25T07:33:50.3319067Z      got: -105.582931
2024-06-25T07:33:50.3319160Z  ; tourMarkers[2].latitude
2024-06-25T07:33:50.3319241Z Expected: 40.130077
2024-06-25T07:33:50.3319315Z      got: 40.136096
2024-06-25T07:33:50.3319411Z  ; tourMarkers[2].longitude
2024-06-25T07:33:50.3319522Z Expected: -105.589888
2024-06-25T07:33:50.3319638Z      got: -105.58185
2024-06-25T07:33:50.3319725Z  ; tourMarkers[3].latitude
2024-06-25T07:33:50.3319810Z Expected: 40.135158
2024-06-25T07:33:50.3319884Z      got: 40.128272
2024-06-25T07:33:50.3319975Z  ; tourMarkers[3].longitude
2024-06-25T07:33:50.3320097Z Expected: -105.556992
2024-06-25T07:33:50.3320205Z      got: -105.592627
2024-06-25T07:33:50.3320297Z  ; tourMarkers[4].latitude
2024-06-25T07:33:50.3320377Z Expected: 40.136586
2024-06-25T07:33:50.3320457Z      got: 40.119869
2024-06-25T07:33:50.3320544Z  ; tourMarkers[4].longitude
2024-06-25T07:33:50.3320659Z Expected: -105.582931
2024-06-25T07:33:50.3320766Z      got: -105.608717
2024-06-25T07:33:50.3320855Z  ; tourMarkers[5].latitude
2024-06-25T07:33:50.3320939Z Expected: 40.136096
2024-06-25T07:33:50.3321056Z      got: 40.130077
2024-06-25T07:33:50.3321148Z  ; tourMarkers[5].longitude
2024-06-25T07:33:50.3321262Z Expected: -105.58185
2024-06-25T07:33:50.3321375Z      got: -105.589888
2024-06-25T07:33:50.3321482Z  ==> expected: <true> but was: <false>
2024-06-25T07:33:50.3321949Z 	at device.garmin.GarminTCX_DeviceDataReaderTests.testTcxImportConeyLake(GarminTCX_DeviceDataReaderTests.java:34)
```

**Comment by FJBDev** [comment]
> There is now a difference between my auto created test file and the created test file on the server.
> 
> I've no idea how to solve this
> 

The best and easiest way to solve this is typically to take the file generated from the failed build, compare it to the old file and replace it it the new one is correct.

I have made a PR to fix all those tests [here](https://github.com/mytourbook/mytourbook/pull/1374), however, what I don't understand is that the unit tests for the Suunto 9 files were also changed. Looking at the new JSON files, it seems that the tour markers are  better now but I don't see any mentions in the readme that the user needs to reimport TCX and Suunto 9 files, which should be important info for the user for the 24.7 release

**Comment by wolfgang-ch** [comment]
> ... I don't see any mentions in the readme that the user needs to reimport TCX and Suunto 9 files, which should be important info for the user for the 24.7 release

There is no need anymore to reimport TCX files. I create the new action "Set Pause Times from Break Time" https://github.com/mytourbook/mytourbook/issues/1372 which can fillup the pause times with the break times, this works for any imported/saved tour

**Comment by wolfgang-ch** [comment]
For missing lat/lon values there was an db update method `net.tourbook.database.TourDatabase.updateDb_024_To_025_DataUpdate()` which was setting these values.

**Comment by FJBDev** [comment]
> For missing lat/lon values in tour markers, there was an db update method `net.tourbook.database.TourDatabase.updateDb_024_To_025_DataUpdate()` which was setting these values.

But what about the altitude values, that doesn't require to reimport the values for Suunto 9 files ?

![image](https://github.com/mytourbook/mytourbook/assets/25235665/b1a208ec-e4cb-416b-84dc-19bd87095cc8)

**Comment by FJBDev** [comment]
> For missing lat/lon values in tour markers, there was an db update method `net.tourbook.database.TourDatabase.updateDb_024_To_025_DataUpdate()` which was setting these values.

And that was added in 2021, so i dont understand why it just recently broke the unit tests for Suunto 9 and TCX files

**Comment by wolfgang-ch** [comment]
> > For missing lat/lon values in tour markers, there was an db update method `net.tourbook.database.TourDatabase.updateDb_024_To_025_DataUpdate()` which was setting these values.
> 
> And that was added in 2021, so i dont understand why it just recently broke the unit tests for Suunto 9 and TCX files

In this commit a37b4b26468c32de19391700a39eed0b0ca91f04 the lat/lon and elevation values are now set when a  tour marker is created
