### ISSUE TITLE
[Bug : Map Points] Is not working anymore with Eclipse 4.32

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1376]
When I use the latest `main`, the tour markers are not displayed in my 2D map and I see this error

![image](https://github.com/mytourbook/mytourbook/assets/25235665/54973143-852e-473f-a71e-d345f2a21d1d)

```

!ENTRY net.tourbook.common 4 0 2024-06-26 22:05:04.776
!MESSAGE Invalid thread access
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Display.error(Display.java:1286)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:863)
	at org.eclipse.swt.widgets.Display.getPrimaryMonitor(Display.java:2245)
	at org.eclipse.swt.widgets.Display.getSystemFont(Display.java:2459)
	at org.eclipse.swt.graphics.Image.internal_new_GC(Image.java:2156)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:171)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:135)
	at de.byteholder.geoclipse.map.Map2.paint_MapPointImage_10_Runnable(Map2.java:6692)
	at de.byteholder.geoclipse.map.Map2.lambda$13(Map2.java:6603)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

_Originally posted by @FJBDev in https://github.com/mytourbook/mytourbook/issues/1369#issuecomment-2192703808_

**Comment by wolfgang-ch** [comment]
I can reproduce this issue when using Eclipse 4.32 but now we have a **BIG** problem.

Map points are painted in a background thread which is using SWT to do all drawings. It seems that the SWT is changed (in Eclipse 4.,32) and do not work anymore in a background thread 👎 

Running the painting task in the foreground thread is not possible it would make the UI very very slow, unusable. An alternative would be to do all paintings with AWT which is already used in a few paintings.

**Comment by FJBDev** [comment]
Indeed, i forgot to mention that i see this error when running MT with Eclipse 2024-06 and not MT 24.7

**Comment by wolfgang-ch** [comment]
I discovered a different Eclipse version because

`at org.eclipse.swt.graphics.Image.internal_new_GC(Image.java:2156)`

points to a comment in Eclipse 4.31 and it was not Linux because in your screenshot there is the win logo

**Comment by wolfgang-ch** [comment]
With AWT, the normal Windows dialog font _Segoe UI_ looks ugly and after many testing I found this issue https://bugs.openjdk.org/browse/JDK-8261524 that a font like _Segoe UI Semibold_ is displayed.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/2bcfb48d-6c6d-49d3-80b3-0c5bb667b06e)


Finally I found the font `Yu Gothic UI` which looks like _Segoe UI_. With the new label font selector (in MT after 24.7) a user can now select what it likes

![image](https://github.com/mytourbook/mytourbook/assets/1283445/e221500d-7b91-4c27-b38f-011950c0f0ed)

**Comment by wolfgang-ch** [comment]
I was already wondering that such an issues is not discovered by other Eclipse users. It is https://github.com/eclipse-platform/eclipse.platform.swt/issues/1288 and is already fixed. 

So with Eclipse 4.33 this should work again, so for now I stop the AWT implementation.

**Comment by wolfgang-ch** [comment]
With the help from an Eclipse developer https://github.com/eclipse-platform/eclipse.platform.swt/issues/1411 the font and image rendering on 4k displays can now be without bluring
