### ISSUE TITLE
Unhandled ArrayIndexOutOfBoundsException exception

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#497]
When using the Statistics view, I see several duplicate exceptions happening

The exception happens in the code [here](https://github.com/FJBDev/mytourbook/blob/210af83f731c5161ff47b634a4ad90dc38ba4454/bundles/net.tourbook.chart/src/net/tourbook/chart/ChartComponentGraph.java#L9907)

MyTourbook Version: **22.3.0**

```
java.lang.ArrayIndexOutOfBoundsException: Index 1096 out of bounds for length 1096
	at net.tourbook.chart.ChartComponentGraph.updateVisibleMinMaxValues(ChartComponentGraph.java:9907)
	at net.tourbook.chart.ChartComponents.setModel(ChartComponents.java:2395)
	at net.tourbook.chart.Chart.updateChart(Chart.java:1420)
	at net.tourbook.statistics.graphs.StatisticDay.updateStatistic(StatisticDay.java:749)
	at net.tourbook.statistic.StatisticView.updateStatistic_10_NoReload(StatisticView.java:1172)
	at net.tourbook.statistic.StatisticView.onSelectYear(StatisticView.java:751)
	at net.tourbook.statistic.StatisticView$7.widgetSelected(StatisticView.java:501)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

**Comment by wolfgang-ch** [comment]
Removed "Bug in Dev" because this can also occure for a normal user
