### ISSUE TITLE
[2.5D / 3D Map] 4k display is not recognized when view is resized

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#503]
**After MT startup**

![image](https://user-images.githubusercontent.com/1283445/161507521-50709582-39d9-4f92-a53f-f34b5cb4ae4b.png)

**After resizing map view**

![image](https://user-images.githubusercontent.com/1283445/161507626-902c5991-5b70-4fdb-b5b9-2725a619f910.png)

**Comment by FJBDev** [comment]
Are you sure that it's because of a 4K display ?

I have the same issue on my laptop and I dont think I use 4K. 
Another user has a noted a similar issue [several weeks ago](https://sourceforge.net/p/mytourbook/discussion/622811/thread/f2afb7cb66/)

My laptop display (not 4K)
![image](https://user-images.githubusercontent.com/25235665/163188477-8a1af4e9-e7a5-4f32-8cc2-b04eee27244d.png)

3D Map issue on my laptop
![image](https://user-images.githubusercontent.com/25235665/163188543-5b4a9253-1d07-4219-af6a-37f8d93deb0a.png)

**Comment by wolfgang-ch** [comment]
This issue happens only on my 4k notebook display but not on my 2560x1440 external monitor

![image](https://user-images.githubusercontent.com/1283445/163209095-c6f151ba-8eb5-4ef6-9b7a-8aed5ecc46bc.png)

**Comment by rr19-hub** [comment]
Same problem here (Lenovo Yoga X1):
![3D-Map A](https://user-images.githubusercontent.com/75927676/163233441-84f98a4f-c746-461a-9a44-9fd85052c609.png)
with: ![3D-Map A2](https://user-images.githubusercontent.com/75927676/163233467-acd63673-7740-4126-a014-f7768cd6d739.png)
and
<img width="847" alt="3D-Map B" src="https://user-images.githubusercontent.com/75927676/163233483-23873ccc-edfe-4c70-9566-3005f98e8d4e.png">
with: ![3D-Map B2](https://user-images.githubusercontent.com/75927676/163233505-b9d3e6d3-16d6-420c-a9b5-6bf12ef0113f.png)

**Comment by JaenVox** [comment]
Ma réalité:
https://ibb.co/N3qBvnG
https://ibb.co/XzyHmMw

**Comment by FJBDev** [comment]
Same issue on my new Lenovo Yoga Pro 9 with Windows 11😞

**Comment by wolfgang-ch** [comment]
Somewhere I found this workaround propably in the 3D map forum because they have the same problem

`"C:\Program Files\MyTourbook\mytourbook.exe" -vmargs -Dsun.java2d.uiScale.enabled=false"`

**Comment by FJBDev** [comment]
> -vmargs -Dsun.java2d.uiScale.enabled=false"

Not only it doesn't work, it creates an error

![image](https://github.com/user-attachments/assets/2adf3020-00f1-4592-bd1c-4fe713908247)

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:171)
	at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
	at com.jogamp.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1513)
	at com.jogamp.opengl.awt.GLCanvas.addNotify(GLCanvas.java:609)
	at java.desktop/java.awt.Container.addImpl(Unknown Source)
	at java.desktop/java.awt.Container.add(Unknown Source)
	at net.tourbook.map3.view.Map3View.createUI(Map3View.java:1097)
	at net.tourbook.map3.view.Map3View.createPartControl(Map3View.java:972)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:987)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:952)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:141)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:395)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:322)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:544)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:528)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:110)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.lambda$27(StackRenderer.java:1110)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3253)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1892)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:332)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

**Comment by yiranlus** [comment]
> Welcome in the 4k club 😎
> 
> Somewhere I found this workaround propably in the 3D map forum because they have the same problem
> 
> `"C:\Program Files\MyTourbook\mytourbook.exe" -vmargs -Dsun.java2d.uiScale.enabled=false"`

I added "-Dsun.java2d.uiScale.enabled=false" to mytourbook.ini. It works.

**Comment by wolfgang-ch** [comment]
> > -vmargs -Dsun.java2d.uiScale.enabled=false"
> 
> Not only it doesn't work, it creates an error

Can you test the different argument which are reported in https://github.com/GateNLP/gate-core/issues/137#issuecomment-765662974

**Comment by FJBDev** [comment]
> > Welcome in the 4k club 😎
> > Somewhere I found this workaround propably in the 3D map forum because they have the same problem
> > `"C:\Program Files\MyTourbook\mytourbook.exe" -vmargs -Dsun.java2d.uiScale.enabled=false"`
> 
> I added "-Dsun.java2d.uiScale.enabled=false" to mytourbook.ini. It works.

It worked, thanks!! 😄

**Comment by wolfgang-ch** [comment]
`mytourbook.ini` is overwritten on every MT installation so I would put it into the command line, which I do.

I already thought to put this setting inside the program code but it may cause issues, so I left it out until now.
