### ISSUE TITLE
[Tour Data Editor View] ArrayIndexOutOfBoundsException when deleting all the time slices

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#509]
I am getting the following exceptions when I select the below feature in the Tour Data Editor View

![image](https://user-images.githubusercontent.com/25235665/162496100-5fb997ee-0a54-4547-9850-1a0aecfd2ca4.png)

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at net.tourbook.map2.view.DirectMappingPainter.drawSliderPath_One(DirectMappingPainter.java:361)
	at net.tourbook.map2.view.DirectMappingPainter.drawSliderPath(DirectMappingPainter.java:192)
	at net.tourbook.map2.view.DirectMappingPainter.paint(DirectMappingPainter.java:487)
	at de.byteholder.geoclipse.map.Map2.onPaint(Map2.java:3520)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1087)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1072)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1536)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4803)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

**Comment by wolfgang-ch** [comment]
@FJBDev The tag `Bug in Dev` should only be set when the bug happens only in the dev environment, this bug would also happen for a user

**Comment by FJBDev** [comment]
I was not able to reproduce it on 22.2 but only in the current main/22.3.0

**Comment by wolfgang-ch** [comment]
For me this is a normal bug which would occure also in the released version when not fixed. 

The tag `Bug in Dev` should be used only for bugs which a normal user would not see, e.g. Unit test bugs https://github.com/mytourbook/mytourbook/issues/436

**Comment by FJBDev** [comment]
Ah, i thought `Bug in Dev` was only for when using MT in Eclipse.

**Comment by wolfgang-ch** [comment]
You may rename this tag that is suits better but this tag should start with "Bug ..."
