### ISSUE TITLE
ClosedByInterruptException

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#863]
Another lucene exception on my MT 22.3.1 Prod

```

java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388)
	at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:242)
	at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:157)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:58)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:688)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:81)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at net.tourbook.search.FTSearchManager.setupIndexReader(FTSearchManager.java:1649)
	at net.tourbook.search.FTSearchManager.updateIndex(FTSearchManager.java:1747)
	at net.tourbook.database.TourDatabase.saveTour_PostSaveActions_Concurrent_2_ForAllTours(TourDatabase.java:3215)
	at net.tourbook.ui.views.rawData.RawDataView.saveImportedTours(RawDataView.java:5375)
	at net.tourbook.ui.views.rawData.RawDataView.runEasyImport_099_SaveTour(RawDataView.java:5111)
	at net.tourbook.ui.views.rawData.RawDataView.runEasyImport(RawDataView.java:4895)
	at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4298)
	at net.tourbook.ui.views.rawData.RawDataView.lambda$14(RawDataView.java:4278)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

**Comment by wolfgang-ch** [comment]
See fix for all Lucene index issues https://github.com/mytourbook/mytourbook/issues/860#issuecomment-1124527192

I don't try to understand Lucene index issues as long as they can be fixed with the upper link, maybe a Lucene jar update may help ?

**Comment by FJBDev** [comment]
> maybe a Lucene jar update may help ?

I am not familiar with Lucene but I see that MT uses a [4+ year old version](https://github.com/mytourbook/mytourbook/blob/8bf3b0ef150c6bc45c061f3212dcfb0f0f6f3e63/bundles/net.tourbook.ext.apache/.classpath#L15). Maybe a jar update would help ?

**Comment by wolfgang-ch** [comment]
>Maybe a jar update would help ?

It may be possible that you have to migrate old code to new code. 
Because Lucene is very complex, this is the reason why I don't try to fix it, when it is working mostly correctly

**Comment by FJBDev** [comment]
> It may be possible that you have to migrate old code to new code. 

Maybe it's too risky then. I will let you decide if it's worth it.

**Comment by wolfgang-ch** [comment]
For now I keep it as it is
