### ISSUE TITLE
[2D Map]  java.lang.NullPointerException

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#872]
Error reported by a MT user (**stvzldn**) to which I gave the link to the pre-release 22.6.0.

I also experienced the same issue on my prod MT 22.6.0 (pre-release)

_I copy below the MTB error log. Note this includes some lines from v22.3.1 that I choose to include since they note a null pointer exception.
There also seems to be a repeating message about setAllViewsClosable=null and a message about category path.
My system is an i9-9900K with 32GB using Win10 LTSC (system is stable with never a crash since built)._

```


!ENTRY net.tourbook.common 1 0 2022-05-31 16:21:24.906
!MESSAGE 2022-05-31T16:21:24.876344600 Setting all views closeable="true" in workbench.xmi
2022-05-31T16:21:24.876344600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T16:21:24.906344900 numViews: 48
2022-05-31T16:21:24.906344900 closeable='true' is set in 0 views

!SESSION 2022-05-31 16:48:28.549 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 16:48:29.519
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 16:48:29.529
!MESSAGE 2022-05-31 16:48:29.466'005 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 16:48:47.365
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY org.eclipse.ui 4 0 2022-05-31 16:49:36.407
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
at de.byteholder.geoclipse.map.Map2.setZoom(Map2.java:7281)
at de.byteholder.geoclipse.map.Map2.zoomOut(Map2.java:7779)
at de.byteholder.geoclipse.map.Map2.onMouse_Wheel(Map2.java:3487)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1087)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1072)
at org.eclipse.swt.widgets.Widget.sendMouseEvent(Widget.java:1133)
at org.eclipse.swt.widgets.Widget.sendMouseWheelEvent(Widget.java:1212)
at org.eclipse.swt.widgets.Widget.wmMouseWheel(Widget.java:2139)
at org.eclipse.swt.widgets.Control.WM_MOUSEWHEEL(Control.java:5318)
at org.eclipse.swt.widgets.Scrollable.wmScrollWheel(Scrollable.java:377)
at org.eclipse.swt.widgets.Scrollable.WM_MOUSEWHEEL(Scrollable.java:349)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4794)
at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5015)
at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
at org.eclipse.jface.window.Window.open(Window.java:799)
at de.byteholder.geoclipse.preferences.PrefPage_Map2_Providers.openConfigDialog_Custom(PrefPage_Map2_Providers.java:2644)
at de.byteholder.geoclipse.preferences.PrefPage_Map2_Providers.openConfigDialog(PrefPage_Map2_Providers.java:2618)
at de.byteholder.geoclipse.preferences.PrefPage_Map2_Providers$2.widgetSelected(PrefPage_Map2_Providers.java:913)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
at org.eclipse.jface.window.Window.open(Window.java:799)
at net.tourbook.common.action.ActionOpenPrefDialog.run(ActionOpenPrefDialog.java:105)
at net.tourbook.map2.view.SlideoutMap2_MapProvider$1.run(SlideoutMap2_MapProvider.java:449)
at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1063)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
at net.tourbook.application.Application.start(Application.java:35)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY net.tourbook.common 1 0 2022-05-31 16:50:32.694
!MESSAGE 2022-05-31T16:50:32.644720600 Setting all views closeable="true" in workbench.xmi
2022-05-31T16:50:32.644720600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T16:50:32.694720200 numViews: 48
2022-05-31T16:50:32.694720200 closeable='true' is set in 0 views

!SESSION 2022-05-31 17:34:20.560 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 17:34:21.540
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 17:34:21.550
!MESSAGE 2022-05-31 17:34:21.486'880 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 17:34:49.750
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 17:35:27.259
!MESSAGE 2022-05-31T17:35:27.229824800 Setting all views closeable="true" in workbench.xmi
2022-05-31T17:35:27.229824800 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T17:35:27.259823700 numViews: 48
2022-05-31T17:35:27.259823700 closeable='true' is set in 0 views

!SESSION 2022-05-31 17:35:35.521 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 17:35:36.471
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 17:35:36.471
!MESSAGE 2022-05-31 17:35:36.414'267 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 17:35:50.876
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 17:50:05.810
!MESSAGE 2022-05-31T17:50:05.780582600 Setting all views closeable="true" in workbench.xmi
2022-05-31T17:50:05.780582600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T17:50:05.810582500 numViews: 48
2022-05-31T17:50:05.810582500 closeable='true' is set in 0 views

!SESSION 2022-05-31 18:30:58.958 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 18:30:59.948
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 18:30:59.958
!MESSAGE 2022-05-31 18:30:59.895'088 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 18:31:20.860
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 18:34:22.914
!MESSAGE 2022-05-31T18:34:22.884740600 Setting all views closeable="true" in workbench.xmi
2022-05-31T18:34:22.884740600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T18:34:22.914740 numViews: 48
2022-05-31T18:34:22.914740 closeable='true' is set in 0 views

!SESSION 2022-05-31 19:03:49.535 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 19:03:50.525
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 19:03:50.525
!MESSAGE 2022-05-31 19:03:50.466'414 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 19:04:00.213
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 19:04:24.146
!MESSAGE 2022-05-31T19:04:24.116077600 Setting all views closeable="true" in workbench.xmi
2022-05-31T19:04:24.116077600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T19:04:24.146077500 numViews: 48
2022-05-31T19:04:24.146077500 closeable='true' is set in 0 views

!SESSION 2022-05-31 19:31:14.835 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 19:31:15.795
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 19:31:15.805
!MESSAGE 2022-05-31 19:31:15.741'894 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 19:31:25.323
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 19:32:51.169
!MESSAGE 2022-05-31T19:32:51.129232 Setting all views closeable="true" in workbench.xmi
2022-05-31T19:32:51.129232 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T19:32:51.169232300 numViews: 48
2022-05-31T19:32:51.169232300 closeable='true' is set in 0 views

!SESSION 2022-05-31 19:37:11.412 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 19:37:12.402
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 19:37:12.402
!MESSAGE 2022-05-31 19:37:12.344'702 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 19:37:26.133
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 19:47:19.965
!MESSAGE 2022-05-31T19:47:19.935941400 Setting all views closeable="true" in workbench.xmi
2022-05-31T19:47:19.935941400 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T19:47:19.965940100 numViews: 48
2022-05-31T19:47:19.965940100 closeable='true' is set in 0 views

!SESSION 2022-05-31 19:53:37.527 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-05-31 19:53:38.517
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-05-31 19:53:38.527
!MESSAGE 2022-05-31 19:53:38.463'743 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-05-31 19:53:47.446
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-05-31 20:06:23.504
!MESSAGE 2022-05-31T20:06:23.464566900 Setting all views closeable="true" in workbench.xmi
2022-05-31T20:06:23.464566900 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-05-31T20:06:23.504566600 numViews: 48
2022-05-31T20:06:23.504566600 closeable='true' is set in 0 views

!SESSION 2022-06-01 11:23:39.413 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-01 11:23:42.384
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-06-01 11:23:42.384
!MESSAGE 2022-06-01 11:23:42.174'598 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-06-01 11:23:54.770
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-06-01 11:27:41.082
!MESSAGE 2022-06-01T11:27:41.032612600 Setting all views closeable="true" in workbench.xmi
2022-06-01T11:27:41.032612600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-01T11:27:41.072612200 numViews: 48
2022-06-01T11:27:41.072612200 closeable='true' is set in 0 views

!SESSION 2022-06-01 11:30:04.462 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-01 11:30:05.442
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-06-01 11:30:05.452
!MESSAGE 2022-06-01 11:30:05.240'641 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-06-01 11:30:13.050
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-06-01 11:31:10.974
!MESSAGE 2022-06-01T11:31:10.944706100 Setting all views closeable="true" in workbench.xmi
2022-06-01T11:31:10.944706100 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-01T11:31:10.974705500 numViews: 48
2022-06-01T11:31:10.974705500 closeable='true' is set in 0 views

!SESSION 2022-06-02 12:54:46.617 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-02 12:54:49.618
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-06-02 12:54:49.628
!MESSAGE 2022-06-02 12:54:49.565'858 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY net.tourbook.common 1 0 2022-06-02 13:01:09.544
!MESSAGE 2022-06-02T13:01:09.504664600 Setting all views closeable="true" in workbench.xmi
2022-06-02T13:01:09.504664600 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-02T13:01:09.544664800 numViews: 48
2022-06-02T13:01:09.544664800 closeable='true' is set in 0 views

!SESSION 2022-06-03 08:26:23.827 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-03 08:26:26.837
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-06-03 08:26:26.847
!MESSAGE 2022-06-03 08:26:26.787'493 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY net.tourbook.common 1 0 2022-06-03 08:29:17.195
!MESSAGE 2022-06-03T08:29:17.155902100 Setting all views closeable="true" in workbench.xmi
2022-06-03T08:29:17.155902100 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-03T08:29:17.195899500 numViews: 48
2022-06-03T08:29:17.195899500 closeable='true' is set in 0 views

!SESSION 2022-06-03 12:29:09.150 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-03 12:29:12.220
!MESSAGE [AppVersion] 22.3.1.20220412-0515

!ENTRY net.tourbook.common 1 0 2022-06-03 12:29:12.220
!MESSAGE 2022-06-03 12:29:12.161'665 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY net.tourbook.common 1 0 2022-06-03 12:31:09.947
!MESSAGE 2022-06-03T12:31:09.907491 Setting all views closeable="true" in workbench.xmi
2022-06-03T12:31:09.907491 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-03T12:31:09.947489300 numViews: 48
2022-06-03T12:31:09.947489300 closeable='true' is set in 0 views

!SESSION 2022-06-04 09:30:09.772 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-04 09:30:15.683
!MESSAGE [AppVersion] 22.6.0.20220604-0525

!ENTRY net.tourbook.common 1 0 2022-06-04 09:30:15.693
!MESSAGE 2022-06-04 09:30:15.634'512 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY net.tourbook.common 1 0 2022-06-04 09:36:36.911
!MESSAGE 2022-06-04T09:36:36.881742100 Setting all views closeable="true" in workbench.xmi
2022-06-04T09:36:36.881742100 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-04T09:36:36.911741900 numViews: 48
2022-06-04T09:36:36.911741900 closeable='true' is set in 0 views

!SESSION 2022-06-04 13:00:47.064 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-04 13:00:50.264
!MESSAGE [AppVersion] 22.6.0.20220604-0525

!ENTRY net.tourbook.common 1 0 2022-06-04 13:00:50.274
!MESSAGE 2022-06-04 13:00:50.217'713 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY net.tourbook.common 1 0 2022-06-04 13:07:32.820
!MESSAGE 2022-06-04T13:07:32.780995300 Setting all views closeable="true" in workbench.xmi
2022-06-04T13:07:32.780995300 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-04T13:07:32.820994900 numViews: 48
2022-06-04T13:07:32.820994900 closeable='true' is set in 0 views

!SESSION 2022-06-04 13:17:23.235 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-04 13:17:26.165
!MESSAGE [AppVersion] 22.6.0.20220604-0525

!ENTRY net.tourbook.common 1 0 2022-06-04 13:17:26.175
!MESSAGE 2022-06-04 13:17:26.118'394 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-06-04 13:17:48.130
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-06-04 13:20:57.810
!MESSAGE 2022-06-04T13:20:57.780729500 Setting all views closeable="true" in workbench.xmi
2022-06-04T13:20:57.780729500 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-04T13:20:57.810730100 numViews: 48
2022-06-04T13:20:57.810730100 closeable='true' is set in 0 views

!SESSION 2022-06-04 13:29:38.777 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-04 13:29:39.752
!MESSAGE [AppVersion] 22.6.0.20220604-0525

!ENTRY net.tourbook.common 1 0 2022-06-04 13:29:39.764
!MESSAGE 2022-06-04 13:29:39.700'973 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"

!ENTRY org.eclipse.ui 2 2 2022-06-04 13:29:53.006
!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)

!ENTRY net.tourbook.common 1 0 2022-06-04 13:32:05.644
!MESSAGE 2022-06-04T13:32:05.624744700 Setting all views closeable="true" in workbench.xmi
2022-06-04T13:32:05.624744700 workbenchFolderPath: C:\Users\sz\mytourbook.metadata.plugins\org.eclipse.e4.workbench
2022-06-04T13:32:05.644744 numViews: 48
2022-06-04T13:32:05.644744 closeable='true' is set in 0 views

!SESSION 2022-06-04 18:25:41.298 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.13
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments: -os win32 -ws win32 -arch x86_64

!ENTRY net.tourbook.common 1 0 2022-06-04 18:25:44.478
!MESSAGE [AppVersion] 22.6.0.20220604-0525

!ENTRY net.tourbook.common 1 0 2022-06-04 18:25:44.488
!MESSAGE 2022-06-04 18:25:44.424'177 [System Property - ApplicationWorkbenchAdvisor] - "setAllViewsClosable=null" -> When "false" then all views will not be set closeable="true" in workbench.xmi when the app closes, recognized value: "true"
```

**Comment by wolfgang-ch** [comment]
>I copy below the MTB error log. Note this includes some lines from v22.3.1 that I choose to include since they note a null pointer exception.

This case should not happen because when restored then it's set to a default when not available https://github.com/mytourbook/mytourbook/blob/347d7c47f777fddbc020d52df82003f533af268a/bundles/net.tourbook/src/net/tourbook/map2/view/Map2View.java#L4026-L4031 but I fixed it

>There also seems to be a repeating message about setAllViewsClosable=null 

this is just logging https://github.com/mytourbook/mytourbook/blob/347d7c47f777fddbc020d52df82003f533af268a/bundles/net.tourbook/src/net/tourbook/application/ApplicationWorkbenchAdvisor.java#L51-L56

>and a message about category path

This message is since a very long time

`!MESSAGE Invalid preference category path: org.eclipse.ui.preferencePages.Workbench (bundle: org.eclipse.equinox.security.ui, page: org.eclipse.equinox.security.ui.category)
`
