### ISSUE TITLE
MTB 22.6.0 Bug with Tags Filter ?

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#885]
Hello,

with the 22.6 release I get an error message (SQL error) each time I try to use the Tags Filter.
This is the log :

!ENTRY net.tourbook.common 4 0 2022-06-17 10:00:43.362
!MESSAGE SQL statement: 

1   
2   SELECT
3      StartYear,
4      SUM( CAST(TourDistance AS BIGINT)),
5   SUM( CAST(TourDeviceTime_Elapsed AS BIGINT)),
6   SUM( CAST(TourComputedTime_Moving AS BIGINT)),
7   SUM( CAST(TourAltUp AS BIGINT)),
8   SUM( CAST(TourAltDown AS BIGINT)),
9   SUM(1),
10   MAX(MaxSpeed),
11   MAX(MaxAltitude),
12   MAX(MaxPulse),
13   AVG( CASE WHEN AvgPulse = 0         THEN NULL ELSE AvgPulse END), 
14   AVG( CASE WHEN AvgCadence = 0       THEN NULL ELSE DOUBLE(AvgCadence) * CadenceMultiplier END),
15   AVG( CASE WHEN weather_Temperature_Average_Device = 0   THEN NULL ELSE DOUBLE(weather_Temperature_Average_Device) / TemperatureScale END),
16   AVG( CASE WHEN Weather_Wind_Direction = 0 THEN NULL ELSE Weather_Wind_Direction END), 
17   AVG( CASE WHEN Weather_Wind_Speed = 0 THEN NULL ELSE Weather_Wind_Speed END), 
18   AVG( CASE WHEN RestPulse = 0        THEN NULL ELSE RestPulse END), 
19   SUM( CAST(Calories AS BIGINT)),
20   SUM( CAST(Power_TotalWork AS BIGINT)),
21   SUM( CAST(NumberOfTimeSlices AS BIGINT)),
22   SUM( CAST(NumberOfPhotos AS BIGINT)),
23   SUM( CAST(FrontShiftCount AS BIGINT)),
24   SUM( CAST(RearShiftCount AS BIGINT)),
25   SUM( CAST(Surfing_NumberOfEvents AS BIGINT)),
26   SUM( CAST(cadenceZone_SlowTime AS BIGINT)),
27   SUM( CAST(cadenceZone_FastTime AS BIGINT)),
28   AVG( CASE WHEN cadenceZones_DelimiterValue = 0 THEN NULL ELSE cadenceZones_DelimiterValue END),
29   MIN( CASE WHEN weather_Temperature_Min_Device = 0 THEN NULL ELSE weather_Temperature_Min_Device END),
30   MAX( CASE WHEN weather_Temperature_Max_Device = 0 THEN NULL ELSE weather_Temperature_Max_Device END),
31   SUM( CAST(tourDeviceTime_Recorded AS BIGINT)),
32   SUM( CAST(tourDeviceTime_Paused AS BIGINT)),
33   AVG( CASE WHEN weather_Temperature_Average = 0   THEN NULL ELSE DOUBLE(weather_Temperature_Average) / TemperatureScale END)FROM (
34      SELECT
35         DISTINCT TourId,
36         StartYear,
37         TourDistance,
38   TourDeviceTime_Elapsed,
39   TourComputedTime_Moving,
40   TourAltUp,
41   TourAltDown,
42   MaxAltitude,
43   MaxPulse,
44   MaxSpeed,
45   AvgCadence,
46   AvgPulse,
47   weather_Temperature_Average_Device,
48   CadenceMultiplier,
49   TemperatureScale,
50   Weather_Wind_Direction,
51   Weather_Wind_Speed,
52   Calories,
53   RestPulse,
54   Power_TotalWork,
55   NumberOfTimeSlices,
56   NumberOfPhotos,
57   FrontShiftCount,
58   RearShiftCount,
59   surfing_NumberOfEvents,
60   cadenceZone_SlowTime,
61   cadenceZone_FastTime,
62   cadenceZones_DelimiterValue,
63   weather_Temperature_Min_Device,
64   weather_Temperature_Max_Device,
65   tourDeviceTime_Recorded,
66   tourDeviceTime_Paused
67      FROM TOURDATA
68      LEFT JOIN TOURDATA_TOURTAG jTdataTtag   ON TourData.tourId = jTdataTtag.TourData_tourId
69      WHERE 1=1 
70   AND TourData.tourPerson_personId = ?
71    AND jTdataTtag.TourTag_tagId IN ( ?)
72   ) NecessaryNameOtherwiseItDoNotWork
73   GROUP BY ROLLUP(StartYear)
74   ORDER BY StartYear

SQLException

SQLState: 42X04
ErrorCode: 30000
Message: Column 'WEATHER_TEMPERATURE_AVERAGE' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'WEATHER_TEMPERATURE_AVERAGE' is not a column in the target table.

!ENTRY net.tourbook.common 4 0 2022-06-17 10:00:43.363
!MESSAGE Column 'WEATHER_TEMPERATURE_AVERAGE' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'WEATHER_TEMPERATURE_AVERAGE' is not a column in the target table.
!STACK 0
ERROR 42X04: Column 'WEATHER_TEMPERATURE_AVERAGE' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'WEATHER_TEMPERATURE_AVERAGE' is not a column in the target table.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ColumnReference.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.ColumnReference.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.BinaryOperatorNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.BinaryComparisonOperatorNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.ValueNodeList.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.ConditionalNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.UnaryOperatorNode.bindOperand(Unknown Source)
	at org.apache.derby.impl.sql.compile.AggregateNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.ResultColumn.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.ResultColumnList.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask.run(GooGooStatementCache.java:525)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)

**Comment by wolfgang-ch** [comment]
This happens also in my MT 22.6

**Comment by wolfgang-ch** [comment]
I found this issue in the code by adding `WEATHER_TEMPERATURE_AVERAGE` but I'm wondering why MT 22.3.1 worked and MT 22.6 not.

I'll create a new version

![image](https://user-images.githubusercontent.com/1283445/174291627-2a4d785b-8de2-492a-b091-456edc876cc3.png)

**Comment by wolfgang-ch** [comment]
@FJBDev In this commit 76d5dea8c4bf6281a98ba9d3153f74099fe33d77 after 22.3.1, you have added the field `WEATHER_TEMPERATURE_AVERAGE` into `net.tourbook.ui.views.tourBook.TVITourBookItem.SQL_SUM_COLUMNS` but it was not added into `net.tourbook.ui.views.tourBook.TVITourBookItem.SQL_SUM_FIELDS`

**Comment by FJBDev** [comment]
> @FJBDev In this commit [76d5dea](https://github.com/mytourbook/mytourbook/commit/76d5dea8c4bf6281a98ba9d3153f74099fe33d77) after 22.3.1, you have added the field `WEATHER_TEMPERATURE_AVERAGE` into `net.tourbook.ui.views.tourBook.TVITourBookItem.SQL_SUM_COLUMNS` but it was not added into `net.tourbook.ui.views.tourBook.TVITourBookItem.SQL_SUM_FIELDS`

Correct, an error on my part. And like I said above, my UI tests could have prevented that from happening.
