### ISSUE TITLE
[JUnit Test] Failed propably because of year 2023 which is now also an item in the year combo box

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#978]
@FJBDev It seems that this test depends on the running year

```
org.opentest4j.MultipleFailuresError: Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: expected: <11> but was: <12>
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:80)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:44)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:38)
	at org.junit.jupiter.api.Assertions.assertAll(Assertions.java:2911)
	at views.StatisticsViewTests.testStatisticsView(StatisticsViewTests.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
https://github.com/mytourbook/mytourbook/blob/8e72711de10021d03a166cda23d57a2dced7f081/bundles/net.tourbook.ui.tests/src/test/views/StatisticsViewTests.java#L46-L49

**Comment by FJBDev** [comment]
I will look at it and fix it soon (when i come back from vacation :)

**Comment by FJBDev** [comment]
Fixed in this [PR](https://github.com/mytourbook/mytourbook/pull/981)
