### ISSUE TITLE
[Bug : Tour Blog View] NullPointerException when trying to save a tour

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#990]
### What happened ?

When saving a modification done in the Tour Data Editor View with the Tour Blog View open, this NPE occurs:

`Command 'command.net.tourbook.tour.SaveTour' failed`

### Version

22.11

### System

Linux

### Relevant log output

```shell
org.eclipse.core.commands.ExecutionException: Error executing 'command.net.tourbook.tour.SaveTour': java.lang.NullPointerException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 33 more
Caused by: java.lang.NullPointerException
	at net.tourbook.ui.views.TourBlogView$4.tourChanged(TourBlogView.java:272)
	at net.tourbook.tour.TourManager.fireEvent_Final(TourManager.java:1383)
	at net.tourbook.tour.TourManager.fireEvent(TourManager.java:1360)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.saveTourIntoDB(TourDataEditorView.java:8107)
	at net.tourbook.ui.views.tourDataEditor.TourDataEditorView.doSave(TourDataEditorView.java:6192)
	at net.tourbook.commands.SaveTour_Handler.execute(SaveTour_Handler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 37 more
```

**Comment by FJBDev** [comment]
While I have made a [temporary fix](https://github.com/FJBDev/mytourbook/pull/107/commits/c4085a12eedfb9db5e810afacb7fbdaaa7cf9430#r1094581826) for this issue that will be in my next PR, I haven't found the underlying reason why TourData can become null

**Comment by wolfgang-ch** [comment]
I'm also seeing sometimes NPE's, I fix them and don't care when I cannot see the reason. 

![fixed-NPEs](https://user-images.githubusercontent.com/1283445/216569358-4e39e132-bebe-49e7-87dd-30aa29e51617.png)

**Comment by FJBDev** [comment]
> I'm also seeing sometimes NPE's, I fix them and don't care when I cannot see the reason.
> 

Ok, so i can close this issue whenever I have pushed my PR for this NPE ? You don't need to know the reason why the NPE occurs ?

**Comment by wolfgang-ch** [comment]
> > I'm also seeing sometimes NPE's, I fix them and don't care when I cannot see the reason.
> 
> Ok, so i can close this issue whenever I have pushed my PR for this NPE ? 

Yes

> You don't need to know the reason why the NPE occurs ?

I'm looking into the code but mostly you cannot find the reason why the exception occurred, except when you are developing new code or modify existing code
