### ISSUE TITLE
[Bug : Map Models] 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#993]
### What happened ?

After updating to the [latest main](https://github.com/mytourbook/mytourbook/commit/1c43cf80c2ad2e1e8297e324b5b65ea3e4370cc0), I get this NPE today

### Version

23.next

### System

Windows

### Relevant log output

```shell
java.lang.NullPointerException
	at net.tourbook.map.model.MapModelManager.saveState_10_Options(MapModelManager.java:316)
	at net.tourbook.map.model.MapModelManager.saveState(MapModelManager.java:305)
	at net.tourbook.map.player.MapPlayerManager.saveState(MapPlayerManager.java:893)
	at net.tourbook.application.ApplicationWorkbenchWindowAdvisor.preWindowShellClose(ApplicationWorkbenchWindowAdvisor.java:547)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$2(WorkbenchWindow.java:503)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.lambda$4(WBWRenderer.java:570)
	at org.eclipse.swt.events.ShellListener$2.shellClosed(ShellListener.java:102)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:102)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:693)
	at org.eclipse.swt.widgets.Shell.gtk_delete_event(Shell.java:1532)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2422)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6832)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6114)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1552)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4474)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

```

java.lang.Exception: Default map model file is not in bundle: /map-models/default-map-models.xml
	at net.tourbook.map.model.MapModelManager.getAbsoluteFilePath(MapModelManager.java:124)
	at net.tourbook.map.model.MapModelManager.restoreState(MapModelManager.java:180)
	at net.tourbook.map.model.MapModelManager.getAllModels(MapModelManager.java:141)
	at net.tourbook.map.model.MapModelManager.getSelectedModel(MapModelManager.java:165)
	at net.tourbook.map.model.MapModelManager.saveState_10_Options(MapModelManager.java:316)
	at net.tourbook.map.model.MapModelManager.saveState(MapModelManager.java:305)
	at net.tourbook.map.player.MapPlayerManager.saveState(MapPlayerManager.java:893)
	at net.tourbook.application.ApplicationWorkbenchWindowAdvisor.preWindowShellClose(ApplicationWorkbenchWindowAdvisor.java:547)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$2(WorkbenchWindow.java:503)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.lambda$4(WBWRenderer.java:570)
	at org.eclipse.swt.events.ShellListener$2.shellClosed(ShellListener.java:102)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:102)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:693)
	at org.eclipse.swt.widgets.Shell.gtk_delete_event(Shell.java:1532)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2422)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6832)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6114)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1552)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4474)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

`java.lang.NullPointerException
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:224)
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:242)
	at org.eclipse.ui.part.WorkbenchPart.dispose(WorkbenchPart.java:105)
	at net.tourbook.ui.views.calendar.CalendarView.dispose(CalendarView.java:433)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:264)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:421)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:452)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:161)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:83)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:103)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:68)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:163)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:163)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:163)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:163)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:102)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:144)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:949)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by wolfgang-ch** [comment]
The question is, why can the file `/map-models/default-map-models.xml` is not loaded. I just tested the current main branch on my Ubuntu 20.04 and this file could be loaded. 

Maybe the leading `/` is a problem with your Linux?

![image](https://user-images.githubusercontent.com/1283445/217452238-20201998-54fe-4967-ac53-639ffa372ed5.png)

**Comment by FJBDev** [comment]
> The question is, why is the file `/map-models/default-map-models.xml` not loaded. I just tested the current main branch on my Ubuntu 20.04 and this file could be loaded.
> 
> Maybe the leading `/` is a problem with your Linux?

What should be the absolute file path of this file ?

**Comment by wolfgang-ch** [comment]
`net.touorbook`  bundle contains new files for the default map models, this also contains the file `default-map-models.xml`

![image](https://user-images.githubusercontent.com/1283445/217573285-bf42f198-42f8-4850-854b-664b596eb3ba.png)

**Comment by wolfgang-ch** [comment]
> What should be the absolute file path of this file ?

With `Everything` you can easily find any files anywhere on your computer, I use it very often

![image](https://user-images.githubusercontent.com/1283445/217576860-6f6c8f9b-2921-48b0-b36c-6dfb9e03fe13.png)

**Comment by FJBDev** [comment]
With [Astrogrep](https://astrogrep.sourceforge.net/download/), I don't find this file.

![image](https://user-images.githubusercontent.com/25235665/217599445-224c1ce9-5cce-45c3-a37e-e53f0f6165fa.png)


I should specify that I tried the latest `main` after creating a Linux Installer and looking at this [build.properties](https://github.com/mytourbook/mytourbook/blob/main/bundles/net.tourbook/build.properties) maybe the map-models folder needs to be added ?
because when I open the `net.tourbook.jar`, I don't see the `map-models` folder

![image](https://user-images.githubusercontent.com/25235665/217599808-e90bcea7-b618-4053-9891-363ad1b2a216.png)

**Comment by wolfgang-ch** [comment]
You already have found the correct fix by adding this folder to build.properties.  😄 

I've not tested it but it should work now. I was not aware that you test MT with created build files but I've discovered this issue when I've had created and tested MT 23.next

**Comment by FJBDev** [comment]
> . I was not aware that you test MT with created build files but I've discovered this issue when I've had created and tested MT 23.next

I typically don't but in this case I wanted to test my new linux environment and thought I would take the latest main to test your 2.5D map improvements
